#import "@preview/mousse-notes:1.0.0": *
#import "@preview/physica:0.9.8": *
#import "@local/tool-box-louis:1.0.0" as tool

#set page(paper: "us-letter")
#show: book.with(
  subtitle: [Bounding Entanglement Locality in Multi-Prover Interactive Proofs],
  author: "Louis TRIOULEYRE-ROBERJOT",
  // epigraph: quote(
  //   attribution: [Jonathan Bingus],
  // )[This is a tremendously inspirational quote that sets the tone of this course; truly, one of the epigraphs of all time.],
)

// Useful command : definition, theorem,
// glue, qed, tablef
//
//
//
//

#import "@preview/dashy-todo:0.1.3": todo

#set par(spacing: 1.2em, first-line-indent: 0pt)

#let mipstarkn = $"MIP"_0^* (k,n)$
#let mipstar = $"MIP"^*$
#let mipstarzero = $"MIP"^*_0$
#let lmip0 = $"LMIP"^*_0$
#let lmip = $"LMIP"^*$
#let RE = $"RE"$

= Introduction and definition

== Definition of $lmip0 [k,n]$, first proposition.

The equality $mipstar = RE$ established by Ji, Natarajan, Vidick, Wright and Yuen @JNVWY reveals that entangled multi-prover interactive proofs are extraordinarily powerful: every recursively enumerable language admits such a proof. The standard model places no constraint on the entanglement shared by the provers — the shared quantum state may be arbitrary, in arbitrary dimension. This paper asks a natural structural question: _what happens when the shared entanglement is constrained to be local?_

We introduce a localized model $lmip0 [k,n]$ — for _Localized_ $mipstar$ — in which the provers share $n$ independent copies of a fixed quantum resource, but each interaction is restricted to a bounded-size *window* of that resource. Concretely, in each round the verifier selects a *fresh* copy and opens a window of at most $k$ qubits (distributed among the provers); the provers' answers for that round must be generated by measurements supported on the opened qubits only. If the verifier wants to test two different windows, it must do so in two rounds (and hence spend two independent copies). This enforces a clean separation between *local correlation size* (the parameter $k$) and *repetition budget* (the parameter $n$).

The full parameterization of the model is $lmip0 (r, p) [k, n]$, where $(r, p)$ are the standard interactive proof parameters — number of provers, rounds, completeness, and soundness — and $[k, n]$ are the _locality parameters_: $k$ bounds the number of qubits that can be jointly accessed in a single round (hence an effective per-round Hilbert space dimension at most $2^k$), and $n$ is the number of independent copies of the resource available to the protocol. The use of square brackets for the locality parameters distinguishes them syntactically from the standard parameters in parentheses. The base class is then defined by taking unions:
$ lmip0 [k,n] = union.big_(r,p) lmip0 (r, p)[k,n], $
$ lmip0 = union.big_(k,n) lmip0 [k,n]. $

In an analog way to the difference between $mipstar$ and $mipstarzero$, we have $lmip$ and $lmip0$. We choose to focus on $lmip0$ because we have a combinatorial approach, then we don't want randomness.
The interest of this model rests on a precise observation. The proof that $mipstar = RE$ requires the shared entangled state to have _arbitrarily large dimension_, growing with the instance. By bounding the amount of entanglement that can be operationally mobilized in a single interaction (at most $k$ qubits), and by enforcing that each round draws from a fresh independent copy, we impose an explicit locality-and-budget structure on the usable correlations. The resulting hierarchy in $[k, n]$ interpolates between constant-dimensional nonlocal games and the full power of $mipstar$, and raises concrete threshold questions: for which growth rates of $k$ and $n$ (as functions of the input size) does $lmip [k,n]$ recover $RE$?

We begin by recalling the formal definition of $mipstar$ and the key theorems that motivate our model.

= Formal definition of $mipstar$

#let HH = $cal(H)$

== General definition

We recall the standard definition of multi-prover interactive proof systems with entanglement. The parameters are the number of provers $r$, the number of rounds $p$, the completeness parameter $c$, and the soundness parameter $s$.

*Definition 1* ($mipstar_0 (r, p)$). A language $cal(L)$ belongs to $mipstar (r, p)$ if there exists a polynomial-time verifier $V$ interacting with $r$ non-communicating provers $P_1, dots, P_r$ over $p$ rounds of communication, such that:

+ *Shared entanglement.* Before the protocol begins, the provers share an arbitrary quantum state
  $ ket(psi) in HH_1 times.o HH_2 times.o dots.c times.o HH_r $
  where each $HH_i$ is a Hilbert space of _arbitrary finite dimension_. No restriction is placed on $ket(psi)$: it may be entangled in any way, in any dimension.

+ *Strategy.* Upon receiving question $q_i$ from the verifier, prover $P_i$ performs a measurement $\{M^((i))_(a|q_i)\}_a$ on their local subsystem $HH_i$ and returns the outcome $a$. The joint probability of outcomes $(a_1, dots, a_r)$ given questions $(q_1, dots, q_r)$ is
  $ p(a_1, dots, a_r | q_1, dots, q_r) = bra(psi) M^((1))_(a_1|q_1) times.o dots.c times.o M^((r))_(a_r|q_r) ket(psi). $

+ *Completeness.* If $x in cal(L)$, there exist a state $ket(psi)$ and measurements such that $Pr[V "accepts"] >= 1$ (we have $c=1$).

+ *Soundness.* If $x in.not cal(L)$, for _every_ state $ket(psi)$ (of every dimension) and _every_ choice of measurements, $Pr[V "accepts"] <= 1/2$ (we have $s = 1/2$).

The class $mipstarzero$ is defined as $union.big_(r,p) mipstarzero (r, p)$, allowing arbitrarily many provers and rounds with perfect completeness and bounded-error soundness.

In the $mipstar$ class, instead of fixing the completeness and soundness parameters to $1$ and $1/2$, we take unions over all $c, s$ such that $c - s >= 1/"poly"(|x|)$, allowing for arbitrary completeness-soundness gaps.

== Two-prover, one-round characterization

A fundamental simplification result shows that two provers and a single round suffice.

*Theorem 1* (see @JNVWY). $mipstarzero = mipstarzero (2, 1)$.

That is, every language recognizable by an entangled multi-prover interactive proof system is already recognizable by a _two-prover, one-round_ protocol with perfect completeness and soundness $1\/2$. In this simplified model, the protocol consists of a single exchange:

#block(inset: (left: 1.5em))[
  1. The verifier samples a pair of questions $(q_A, q_B)$ and sends $q_A$ to prover $A$, $q_B$ to prover $B$.

  2. The provers, who share $ket(psi) in HH_A times.o HH_B$, each measure their subsystem and return answers $a, b$.

  3. The verifier evaluates a predicate $V(q_A, q_B, a, b)$ and accepts or rejects.
]

This is precisely the framework of a _nonlocal game_, and the supremum of the acceptance probability over all quantum strategies is the _entangled value_ $omega^*$ of the game.

== The role of unbounded dimension in $mipstar = RE$

The following is the landmark result that motivates our investigation.

*Theorem 2* (Ji, Natarajan, Vidick, Wright, Yuen @JNVWY). $mipstar (2, 1, 1, s) = RE$ for some constant $s < 1$.

The proof constructs, for each Turing machine $M$, a nonlocal game $cal(G)_M$ such that:
- if $M$ halts, then $omega^*(cal(G)_M) = 1$ (a perfect strategy exists in finite dimension $d$, where $d$ depends on the halting time of $M$);
- if $M$ does not halt, then $omega^*(cal(G)_M) < 1$ (no strategy in any dimension achieves value $1$).

A crucial feature of this construction is that the entangled value is defined as
$ omega^*(cal(G)) = sup_(d >= 1) sup_(ket(psi) in CC^d times.o CC^d) sup_({M_(a|q)}, {N_(b|q')}) Pr["win"], $
and the supremum over $d$ is _essential_. For a halting machine with halting time $T$, the dimension $d$ of the optimal strategy may grow as a function of $T$, and no uniform bound on $d$ exists across all instances. In other words, the full power of $mipstar = RE$ relies on the provers' ability to use shared entanglement of _arbitrarily large dimension_.

*Remark.* If the dimension is bounded by a fixed constant $d$, the resulting class $mipstar (2,1,s,d)$ is known _not_ to capture all of $RE$; indeed, for fixed $d$, the entangled value $omega^*_d (cal(G))$ is computable by semidefinite programming, so the class collapses to a decidable complexity class.

= Definition of $lmip0 [k,n]$

#definition(name: [$lmip0 (r,p)[k,n]$])[

  A language $cal(L)$ belongs to $lmip0 (bold(r),bold(p))[bold(k),bold(n)]$ if there exists a polynomial-time verifier $V$ interacting with $bold(r)$ non-communicating provers $P_1, dots, P_bold(r)$ over $bold(p)$ rounds, such that:

  + *i.i.d. shared resource.* Before the protocol begins, the provers share $n$ independent copies of a fixed $r$-partite quantum state:
    $ ket(Psi) = ket(psi)^(times.o n). $
    Each copy are distributed among the $r$ provers with this following map $π : [n] -> [r]$, then the provers $p in [r]$ has the state $ket(psi)_()$

  + *One fresh copy per round.* The verifier uses at most one copy per round, and never reuses a copy. Formally, the verifier chooses an injective map $t mapsto j_t in [n]$. In particular, necessarily $p <= n$.

  + *Window locality (size $k$).* In each round $t in [p]$, the verifier selects a window $S_t subset [N]$ with $|S_t| <= k$ and sends questions $q_1^t, dots, q_r^t$ to the provers (including, if needed, a description of $S_t$). Each prover $P_i$ must generate their answer $a_i^t$ by a measurement that acts nontrivially only on the qubits of the chosen copy $j_t$ whose labels lie in $S_t$, together with any private workspace. Equivalently, for each prover $P_i$ and each round $t$, every POVM element can be written as
    $ M^((i,t))_(a_i|q_i^t) = tilde(M)^((i,t))_(a_i|q_i^t) times.o I, $
    where $tilde(M)^((i,t))_(a_i|q_i^t)$ acts on prover $P_i$'s qubits in copy $j_t$ with labels in $S_t$, and $I$ is the identity on all other qubits (including all other copies).

  + *Completeness and soundness.* If $x in cal(L)$, there exist a state $ket(psi)$ and a window-local strategy achieving $Pr[V "accepts"] = 1$. If $x in.not cal(L)$, then for every choice of $ket(psi)$ and every window-local strategy, $Pr[V "accepts"] <= 1/2$.

  We define $lmip0 [k,n] = union.big_(r,p) lmip0 (r,p)[k,n]$, and $lmip0 = union.big_(k,n) lmip0 [k,n]$.
]


#pagebreak()

== Jeux du C5

#let mε = text([$frak(epsilon)$], size: 1.5em)
#let mN = $cal(N)$

Le jeux est le suivant, il y 5 joueurs dans un cercle. Chaque joueur reçoit une question $x_i$ et doit donner une réponse $a_i$ selon la règle suivante :
La réponse $a$ doit être tel que :
$( a_(i-1) + a_i + a_(i+1) )( a_(j-1) a_j a_(j+1) ) = 1$ si $(x_(i-1) , x_i, x_(i+1) ) = (0,1,0)$ et $(x_(j-1) , x_j, x_(j+1) ) = (0,1,0)$ et $|i-j mod 5| >= 2$.
$sum_i a_i = 1$ si $forall i , space x_i = 1$.

We can modelize this game with the black-white formalism.
Let $Π = (Σ_Π,mε_Π,mN_Π)$ such that :

$
  mN & = { (C a a_1) (C a a_2) | a ⊕ a_1 ⊕ a_2 = 0 , a,a_1,a_2 in {0,1} } \
     & union { (P a dot) (P a dot) | a in {0,1} } \
     & union { (P a dot) (R a dot) | a in {0,1} } \
     & union { (G¹ 1 overline(a_1 a_2) ) (G¹ 1 overline(b_1 b_2)) | 1 ⊕ ⊕_i a_i ⊕ ⊕_i b_i = 1 , a_i,b_i in {0,1}} \
     & union { (G² a overline(a_1) (G² a overline(b_1)) | a,a_i,b_i in {0,1} } \
     & union { (G³ a dot) (G³ a dot) | a in {0,1}} \
     \
  mε & = { (C a a_1) (P a_1 dot) | a,a_1 in {0,1} } \
     & union { (R a dot) (R a' dot) | a,a' in {0,1} } \
     & union { (G¹ 1 overline(a_1 a_2)) (G² a_1 overline(a_2)) | a_1 , a_2 in {0,1}} \
     & union { (G² a overline(a_1)) (G³ a_1 dot) | a,a_1 in {0,1} } \
     \
   Σ & = mN union mε
$

How to understand this ?
- $C$ correspond au commandant, $P$ est sur le port qui point vers un commandant, $R$ est sur le port qui pointe vers un non commandant.
- $G¹$ est le général de classe 1, le plus puissant, c'est lui qui va donner l'ordre et qui va dessider la valeurs de toute les autres généraux. Chaque généraux d'ordre i suit l'ordre de son général d'ordre $i+1$.

We can see $0 = "Id"$ and $1 = not = X$ like a function (ex : $bb(1)(1) = 0$)
$
  mN_(|C) &= (C a b) (C a bb(a)(b)) | (P a dot) ([P R] a dot)
  \
  mN_(|G) &= (G¹ 1 overline(a_1 bb(s))) (G¹ 1 overline(b_1 bb(s))) | (G² a overline(a_1)) (G² a overline(b_1)) | (G³ a dot) (G³ a dot)
  \ \
  mε_(|C) &= (C a a_1) (P a_1 dot) | (R a dot) (R a' dot) \
  mε_(|G) &= (G¹ 1 overline(a_1 bb(s))) (G² a_1 overline(bb(s)(a_1))) | (G² a overline(a_1)) (G³ a_1 dot)
$

Let note $G_Π$ the hypergraph corresponding to the problem $Π$.

Let $P = { (v,e) | v in V(G_Π) , e in E(G_Π) , v in e}$ the set of pairs vertex-edge such that the vertex is in the edge. If can consider also the bipartite graph $B_Π = (E union.sq V , P)$, you have the node at the right and the edge at the left.

#let sol = $italic("sol")$

A _solution of $Π$_ is a function $sol : P -> Σ_Π$ that label the edge of $B_Π$ or the vertex-edge pair of $P$ are such that:
- $forall v in V(G_Π)$ , let $L = (l_1,dots, l_Δ) = (sol(v, e_1),dots,sol(v, e_Δ))$ _the label of v_, then $exists σ "permutation", σ(L) in mN_Π$
- $forall e in E(G_Π)$ , let $L = (l_1,dots, l_δ) = (sol(v_1, e),dots,sol(v_δ, e))$ _the label of e_, then $exists σ "permutation", σ(L) in mε_Π$

#let out = $italic("out")$

We can define a _solution of $Π$ under question $q = (q_1,dots,q_(|V(G_Π)|))$_ as a function $sol_q : P -> Σ_Π$ solution of $Π$ such that $forall v in V(G_Π), sol(v, dot) subset mN_(Π,|q_v)$.
We define a function $out_v : Σ^(Δ) -> Σ_out$ that define what will be the output of a node with the given label of its incident edges.
For exemple, for a node with label $(C 1 0) (C 1 1)$, the output will be $1$.

We have the following property :
#proposition[
  If (q,a) is the question-answer pair of a winning stategy for the game $C_5$, this is equivalent to the existence of a solution of $Π$ under question $q$ and such that $forall v,space "let" {e_i}_i = N(v), space out_v (sol(v, e_1),dots,sol(v, e_Δ)) = a_v$, i.e. the output of $Π$ for each node is the answer of the corresponding player.
]

This proposition is not very interesting, it just says that the game is encode in the black-white formalism. But now we can use the tools of the black-white formalism to analyze the game.

What means that $Π$ is 0 round solvable ? this means that each node need to set a label on its incident edges without knowing every thing else, without knowing the label or either the name of the other node incident to him. This create a kind of language that will be $[01]^5$, the language of all the possible 0,1 label of the 5 nodes. So the chance that the node create an output that is a solution of $Π$ is very low.

And what means that $Π$ is 1 round solvable ? If the question is for exemple $q = (1,0,0,1,0)$, each node with question $1$ will send during the communication step an order to the node next to him, and because the question is such that the node next to him have question $0$ and don't send order, there are no contradiction order ! Then in 1 round communication we can wins this game with probability 1. Know we are intersest in the case the question is $q = (1,1,1,1,1)$. We can do the following stategy : if my question is $1$ and the question of my neighbor is $1 1$, this means that i am in the case where $q = (1,1,1,1,1)$, so i can simply output $1$ and win because everyone do the same, if my neighbor is $0 0$ i output $0$ and if my question is $0$ and output $0$. This strategy win the game in 1 round of communication !

So this conclude that this notion of communication is too powerful, it express nothing !

==

Let define an lcl probleme like this :
$Σ = {(["XZ"],[01])}$

The black constraints represent the entanglement and the white constraints represent the common measurements (exemple : Bell measurement).

We express that with stabilizer formalism, let take an simpler exemple where we have $Δ = 3$ and $δ = 2$, this means that the black have degree 2 and the white have degree 3.

For each world $x in {0,1}^*$ we can compile it to two stabilizer :
- The _black stabilizer_, in our exemple we will take $S_b = <"XX" , "ZZ" >$
- The _white stabilizer_, in our exemple we will take $S_w = <"XXX" , "ZZI" , "ZIZ" >$

Then we can define the problem $Π_x$ as follow :
$
  mε &= { (M_1,b_1) (M_2,b_2) | "if" (M_1,M_2) = ("X","X") => b_1 ⊕ b_2 = 0 , "if" (M_1,M_2) = ("Z","Z") => b_1 ⊕ b_2 = 0 }
  \
  mN &= { (M_1,b_1) (M_2,b_2) (M_3,b_3) | "if" (M_1,M_2,M_3) = ("X","X","X") => b_1 ⊕ b_2 ⊕ b_3 = s_1 , \ & "if" (M_1,M_2,M_3) = ("Z","Z","I") => b_1 ⊕ b_2 = s_2 , "if" (M_1,M_2,M_3) = ("Z","I","Z") => b_1 ⊕ b_3 = s_3 }
$

The white stabilizer express a GHZ measurement on both two bell state. If the central node transmit the result of this measurement to the two other node, they can transforme two bell state into a GHZ state. But this require one bit of communication.

The question we can ask is what game we can wins with this resource ? We cannot wins the $C_5$ because it require arity of size 3 (GHZ state)


In this exemple the

==

#import "@preview/game-theoryst:0.1.0": nfg

#nfg(
  players: ("Alice", "Bob"),
  s2: ($0 |-> 0$, $0 |-> 1$, $1 |-> 0$, $1 |-> 1$),
  s1: ($0 |-> 0$, $0 |-> 1$, $1 |-> 0$, $1 |-> 1$),
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
)


We can reprensent strategy, for exemple the strategy $I crossproduct bb(1)$ that correspond to a square :

#nfg(
  players: ("Alice", "Bob"),
  s2: ($0 |-> 0 , 0|0$, $0 |-> 1 , 1|0$, $1 |-> 0, 0|1$, $1 |-> 1 , 1|1$),
  s1: ($0 |-> 0 , 0|0$, $0 |-> 1 , 1|0$, $1 |-> 0, 0|1$, $1 |-> 1 , 1|1$),
  [$.$],
  [$1$],
  [$.$],
  [$1$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$.$],
  [$1$],
  [$.$],
  [$1$],
)

We can have also the oposite view, for each point, for each event $e = (a b | x y)$, we have exactly four strategy that contains this event !

Then for each strategy $s in S$ we define the sub square matrix $M_s$ with four one.

#import "@preview/pavemat:0.2.0": pavemat

#let matrix = $mat(., ., ., .; ., ., ., .; ., ., ., .; ., ., ., .)$

We denote $N$ the matrix that count the event that come $e = (a b | x y)$. We start by this initial count :
$
  N = mat(1, 1, 1, 1; 1, 1, 1, 1; 1, 1, 1, 1; 1, 1, 1, 1)
$

then if a event, for exemple $e = (1 0 | 0 0)$ come, we increase the count matrix :
$
  N = mat(1, 1, 1, 1; 2, 1, 1, 1; 1, 1, 1, 1; 1, 1, 1, 1)
$

*Why we count the event that come ?* We can see this like an interative protocol, where a verifier prepare a question and ask to alice and bob. But instead of express a probability we want a trace, an history to express a form of explainable locality. We need to be able to interupt our processe at any time !

But we need to keep a trace of the history, we can either save all the matrix history in a list ${N_t}_t$.

We say that the count $N$ is non signaling if $ N(a 0 | x y) + N(a 1 | x y) = N(a 0 | x y') + N(a 1 | x y') $ for any $a,x,y,y'$.

In our seting, it saying that for each line, the sum of the column 1 and 2 is equal to the sum of the column 3 and 4 and for each column, the sum of the lines 1 and 2 is equal to the sum of lines 3 and 4.

This means that maybe during a time, the comportement we see is the comportement of signaling Alice and Bob, but we expect to be close to a non signaling form !

=== Some algebra

Let $cal(L)_NN = { sum_(s in S) c_s M_s | c_s in NN^*}$ the cone that represent the set of count $N$ such that it is explicable by a combinaison of deterministc strategy. Why ? ...

Let $V(a | x)$ a polynome function that is equal to 1 if that event verify the rule. \
We define $"score"(N) = sum_(x,a) V(a|x) N(a|x)$ the score, but what is this score ? what it means ? \
We have $"score"(M_s) = sum_(x,a) V(a|x) M_s (a|x) = sum_x V(f_1 (x_1) , dots , f_n (x_n) | x )$ because a deterministic strategy is define by a function $f$ for eachs players ! \
Then we have the following relation $"score"(N) = sum_s c_s "score"(M_s)$, we can define $l_s := "score"(M_s)$.

An othen this, if we note the matrix with all one $u$, the initial count is $N_0 = sum_s M_s = 4 u$.

=== Find the normal count.

We observe a count $N$, the goal is to calculate the closest normal count $N^*$ that belong to the cone $cal(L)$.

We can define this MIP that find the normal past count :

$
  max_(c_s) & sum_s c_s M_s \
        s.t & sum_s c_s M_s <= N
$

== Restart !

We want to study interactive protocol, an specialy non local game. But we want to take an other point of view, we want to understand why. Because in the traditionnal model, we say that we have some share ressource and a strategy, and they are a verifier that ask question and receive answer. But it is magig, we don't describe how the interaction happens and how we build this ressource. The consequence is that if we push this model to the limit, we can do thing that is impossible in the real world, for exemple decide the HALT problem.

First we will abstract the background of how the interaction happen and we will suppose directly that we have someone, the narrateur that observe some event (or the event are receive in the narrateur's mind) $e$. The narrateur can receive multiple event, then he can order them with him own time perception ${e_t}$.

We will consider event of this kind $e = (a | x)$ where $a in A_1 crossproduct A_2 dots crossproduct A_n$ and $x in X_1 crossproduct X_2 dots crossproduct X_n$ where $X_i$ is the set of question of player $i$ and $A_j$ the set of answer of player $j$. For example $e = (a b | x y)$ where $a,b in {0,1}$ are the answer of Alice and Bob and $x,y in {0,1}$ are the question of Alice and Bob.

The narrateur can controle the event, he only listen. Maybe he can introduce later actors that can controle the question for example, but for now we will stay simple.

Let define a _trace_ $τ = e_1 e_2 dots e_h$ as a world where the alphabet is the set of event. This means that $τ subset Σ^*$ for $Σ = (A_1 , dots, A_n | X_1 , dots , X_n)$ where $n$ is the number of player that is fixed !

In traditionnal model, we have a probability distribution $p(a b | x y)$ that is purely abstract, we can never observe this quantity directly, but in our model we have a trace $τ$ that is just an observation and we have the property that we can interupt the process at any time.

In the case we are in the classical deterministic model, players has deterministic strategy that is a funcion $f_i (x) = a$ that map the question to the answer. We will take a parallel to the classical setting where alice and bob can share a common random variable $λ$. We have :
$
  p(a b | x y) = sum_λ µ(λ) δ_{a = f_A^λ (x)} δ_{b = f_B^λ (y)}
$
where $µ(λ)$ is the probability distribution of the common random variable and $f_A^λ$ and $f_B^λ$ are the deterministic strategy of Alice and Bob that depend on the common random variable.

In this view point we don't see multiple interation, but we can believe that the common random variable act like a seed, and the deterministic player use this seed to generate strategy that can involve during the time. The players don't have static strategy, but him strategy can evolve during the time. We will say that the *strategy change in a continous way*, this means that if we zoom on a small time window, the strategy of the player is almost constant and a strategy can change only for a strategy that is close to it. This is a form of discret continuity.

We define a _strategy_ $s$ by a function $s : X_1 crossproduct dots crossproduct X_n -> A_1 crossproduct dots crossproduct A_n$ such that $s(x) = a$ is the answer for the question $x$. A strategy is the combination of the local strategy of each player, for example if we have two player Alice and Bob, we can write $s(x,y) = (f_A (x) , f_B (y))$ where $f_A$ is the local strategy of Alice and $f_B$ is the local strategy of Bob.

Let take an exemple of a game at two player, and let draw a representation of the event that come during the game.

Let say that the event $e_1 = (10 | 10)$ arrive, this means that the local strategy of Alice is the either the $1$ or $I$ function and the local strategy of Bob is the either $0$ or $I$ function. We label this set of strategy $s = {1,I} {0,I}$, it is represented by two label that represent the uncertainty of the strategy.

Here we give one possible definition of _coherents local strategy_ : \
We say that two strategy $f in {0,1,I,N}$ and $g in {0,1,I,N}$ are _localy coherents_ if they are the same or they respect this following relation :

#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node

#diagram(
  $0 edge("<->") edge("d", "<->") & I edge("d", "<->") \ N edge("<->") & 1$,
)

This representation are at distance 1 in terme of bit : $0 : 0 |-> 0 and 1 |-> 0$ and $I : 0 |-> 0 and 1 |-> 1$, we change only one bit of the require answer.

We say that two strategy $s$ and $s'$ are _coherents_ and we denote this $s <-> s'$ the fact that if $s = a b$ and $s' = a' b'$ then $a a'$ and $b b'$ have one bit in common and the second bit are localy coherent. Exemple : $I 0 <-> I N$, $I 0 cancel(<->) I 1$ and $I 0 cancel(<->) 0 N$.

Let take an exemple to see the logic, let's say that the strategy for both players are $s_1 = I 0$. For the next step the strategy change in a coherant manner (continuous way), then we will have for exemple $s_2 = I I$.
We denote $e(s_1) subset Σ$ a set of event of size 4 that are possible with the strategy $s_1$. We will represent the set $e(s_1)$ in blue and the set $e(s_2)$ in red.

#let cred(content) = text($content$, fill: rgb(200, 0, 0, 200))
#let cblue(content) = text($content$, fill: rgb(0, 0, 200, 200))
#import "@preview/cetz:0.4.2"
#cetz.canvas(length: 4em, {
  import cetz.draw: *

  let print(aa, bb, arg) = {
    let x = 0.5 + bb
    let y = 3.5 - aa
    content((x, y), arg)
  }

  let conv(aa, bb) = {
    let x = 0.5 + bb
    let y = 3.5 - aa
    (x, y)
  }

  grid(
    (0, 0),
    (4, 4),
  )

  content((-1, 3.5), $1 |-> 0_(cred(0 "," N))$)
  content((-1, 2.5), $0 |-> 0_(cred(0 "," I))$)
  content((-1, 1.5), $1 |-> 1_(cred(1 "," I))$)
  content((-1, 0.5), $0 |-> 1_(cred(1 "," N))$)

  content((0.60, 4.5), $1 |-> 0_(cred(0 "," N))$)
  content((1.60, 4.5), $0 |-> 0_(cred(0 "," I))$)
  content((2.60, 4.5), $0 |-> 0_(cred(1 "," I))$)
  content((3.60, 4.5), $1 |-> 0_(cred(1 "," N))$)


  print(2.2, 1, $cblue(e(s_1))$)
  print(2.2, 0, $cblue(e(s_1))$)
  print(1.2, 1, $cblue(e(s_1))$)
  print(1.2, 0, $cblue(e(s_1))$)

  print(0.8, 0, $cred(e(s_2))$)
  print(1.8, 0, $cred(e(s_2))$)
  print(1.8, 3, $cred(e(s_2))$)
  print(0.8, 3, $cred(e(s_2))$)
  //print(0,3,$e_2$)
})

We can observe two thing : first the set $e(s)$ forms a elementary square, second, two set $e(s)$ and $e(s')$ such that $s <-> s'$ are orthogonal translation in this square modulo 4.

We say that a trace $τ = e_1 dots e_h$ is _localy explainable_ if $∀ t , e_t$ is localy coherent, this can be express by this condition
$
  exists s_- , s , s_+ "strategy" , s <-> s' and e_t in s(e_t) and e_(t-1) in s(e_(t-1)) and e_(t+1) in s(e_(t+1))
$
This means that there exist a strategy that explain $e_t$, and one before and next strategy that explain the before and next event such that this strategy are closes or coherents.

#todo[euh non c'est faux !] But, we can see cleary that if we define coherent strategy like before, any sequence of event (trace) are localy explainable !

Why ? because the key is not the strategy alone ! it is *the dynamics of the uncertainty we have to believe that players do*.

#let close = $op(<->, limits: #true)_a$
We don't know exactly what players do in terms of strategy, but we can express our believe using a set of possible strategy.

This why we can define the uncertaity strategy, that is define with a set of strategy, we denote this set $s = {1,N} {0,I}$. We say that $s close s'$ are _coherents_ or _close_ if the differe by one bit and this difference are coherent for example $s = {0,N} {I,1}$ and $s' = {0,N} {0,1}$ are coherents but not $s = {0,N} {I,1}$ and $s' = {0,N} {I,0}$ neither $s = {0,N} {I,1}$ and $s' = {0,0} {0,1}$.

Then we denote $s(e)$ the set of event that is in all the strategy $s$ in the same time, then this set is of size one. And we remark that with this definition, a trace that is localy explainable is a sequence of event that forms a path is the representation.

We can denote $τ = τ_1 || dots ||τ_k$ a segmented trace that require that each $τ_i$ is localy explainable. In this way we can count the change of comportement and we can express language where the $k$ is bound.

When we use the word *local*, we mean that two behaviours are *close* to each other, in the sense that one can be obtained from the other by a small modification. The main reason for introducing this notion is that, in practice, an observed event does not appear from nowhere. It is produced by an underlying process.

Indeed, an experiment is usually performed through a sequence of elementary steps. At each step, there may be noise, imperfections, small deviations, or even deliberate modifications. What we finally observe is only the outcome of the whole process, not the internal evolution itself. From this point of view, a piece of data should not be seen as an isolated object, but as the visible trace of a hidden sequential mechanism.

This is the reason why we introduce the notion of a *trace* $tau_i$. A trace represents the observable record of a process that is not directly accessible. Our goal is to understand the observed data by postulating constraints on the hidden process that produced it. In particular, we assume that this hidden process evolves in a locally coherent way, meaning that its successive configurations cannot change arbitrarily, but only through small perturbations. This motivates the notion of *local event*.

A local event is therefore not just an observed input-output pair. It represents an elementary observable step that is compatible with a hidden process evolving continuously in a discrete sense. In other words, the randomness that we observe at the level of traces is not taken as primitive. Instead, it is explained as the visible effect of an underlying process whose evolution is constrained by a notion of local continuity.

With this perspective, an experiment or a measurement can be described as a sequence of elementary local events. A single observed datum is then the result of a whole path through the space of locally coherent behaviours.

To connect this idea with interactive protocols, we distinguish between different levels of description. On the one hand, there is the physical implementation of the experiment, which we may think of as a collection of laboratories or devices performing concrete operations. On the other hand, there are agents who communicate with the verifier and may alter, transmit, or reinterpret the information. This distinction is important because the physical process itself may be constrained by locality and continuity, while the communicating agents may behave strategically or even maliciously.

In this interpretation, the laboratory represents the concrete physical process that produces outcomes according to the instructions it receives. The student, or more generally the external agent, acts as an interface between the verifier and the laboratory. This agent may carry the resource, choose how to implement the requested experiment, transmit the answers, and possibly modify the protocol or the reported outcome. The purpose of this distinction is to separate the hidden physical generation of the data from the adversarial layer that may affect what is actually communicated.

Our aim is therefore not only to study which correlations are possible, but also to model how an observed behaviour can be generated through a sequential process subject to local constraints, and how this process may be altered by intermediate agents. This gives a more dynamic point of view on non-local games and interactive protocols.

We can start by a simple model that is, we have a agent that go to different laboratory to do experimentation, he collect the data and return to the verifier. We lost the order of the data, then we can define :

$
  N_τ (e) := |{ t | τ[t] = e }|
$

Then of course if we have the trace, we can compute the count of each event, but is not what we have. We have only the count of the event.

In experimental physics, we first sketch a theoretical model, here our model will be that local event or trace do a path in the representation, then we need to test this model and to do the experimentation and show that it fit the model. So in our case is just verify that $N_"theory" approx N_"experiment"$. But we can do more, instead of just verify a high level property, i.e. property on the distribution, we can try to verify more low level property, for example the procces of generation of the data, the dynamics of the trace. In our case we would like to verify that $"score"(N_"experiment") approx "score"(τ = e_1 dots e_n)$.

#let score = $italic("score")$
One theoritical model we can formulate on the dynamics of the trace is that it make a path in the representation, this is what we formulate with the $s close s'$. So we can create a score function that is the entropy of the experiment $N$ according to the logic of the path. What i means is, we say that we do random walk in the representation and see if this random walk eat (like the pacman) enought event of the experiment $N$. If this is a case, it is highly probable that the experiment $N$ is generate thought random walk in the representation.

#let model = $italic("model")$

Let $model$ the relation between the local event. We can define

$
  score\(hat(N) ; model)= min_(τ in model) sum_e |N_τ (e) - hat(N)(e)|
$

#todo(position: "inline")[
  cela me fait penser a des polynomes ...
]

== Automates

Let's define the notion of _localy explainable_ trace.

Let $cal(A) := (Σ,S,s_0,δ)$ an automate. This automata define the _model_ we want to use, the notion of local we want.

Let's take an exemple: let say that we have four states $S = {0,1,I,N}$ such that :
$
  δ(s,e) = {s' in S | s <-> s "and" e in E(s')}
$
This automata is undeterministic.

Here the all diagram that form a finite automata :

#diagram(
  spacing: 2.5em,
  node((0, 0), $s_0$, name: <s0>, radius: 1.5em, stroke: 1pt),

  node((-1, 1), $q_0$, name: <q0>, radius: 1.5em, stroke: 1pt),
  edge("l,d,r,u", "-|>", $e_0$),
  node((1, 1), $q_1$, name: <q1>, radius: 1.5em, stroke: 1pt),
  edge("r,d,l,u", "-|>", $e_1$),
  node((-1, -1), $q_N$, name: <qN>, radius: 1.5em, stroke: 1pt),
  edge("l,u,r,d", "-|>", $e_N$),
  node((1, -1), $q_I$, name: <qI>, radius: 1.5em, stroke: 1pt),
  edge("r,u,l,d", "-|>", $e_I$),

  edge(<s0>, <q0>, $e_0$, "-|>"),
  edge(<s0>, <q1>, $e_1$, "-|>"),
  edge(<s0>, <qN>, $e_N$, "-|>"),
  edge(<s0>, <qI>, $e_I$, "-|>"),
  edge((0, -1.8), <s0>, "-|>"),

  edge(<q0>, <q1>, $e_1$, "-|>", bend: 20deg),
  edge(<q1>, <q0>, $e_0$, "-|>", bend: 20deg),
  edge(<q1>, <qI>, $e_I$, "-|>", bend: 20deg),
  edge(<qI>, <q1>, $e_1$, "-|>", bend: 20deg),
  edge(<qI>, <qN>, $e_N$, "-|>", bend: 20deg),
  edge(<qN>, <qI>, $e_I$, "-|>", bend: 20deg),
  edge(<qN>, <q0>, $e_0$, "-|>", bend: 20deg),
  edge(<q0>, <qN>, $e_N$, "-|>", bend: 20deg),
)

where $e_s$ denote the set of event $E(s)$.

We can denote this automata $cal(A) = (Σ,S,E)$ where $forall s in S, E(s)$ is the set of event assiate with this state.

Then we say that a _trace_ $τ$ is _localy explainable_ if $τ = e_1 dots e_n in Σ^n$ is in the language define by $A$. We note this $τ in L_A$. We call $A$ the _model_.

The _Parikh vector_ of a word $τ in Σ^n$ is defined by the image of a function $Psi : Σ^* -> NN^k$ such that $Psi(τ) = ( |τ|_e_1, dots , |τ|_e_n)$ where $|τ|_e_i$ denote the number of letter $e_i$ in $τ$.



// mip

Let $hat(N) in NN^n$ an abitrary vector that is a result obtain by the verifieur after the interacting protocol such that $hat(N)[e]$ is the number of times we have record the event $e$.

The goal is to determine wether this result is _localy explainable_ ?

#definition[
  We say that $hat(N)$ is explainable under A if $exists τ in L_A$ such that $Psi(τ) = hat(N)$.
]

We can define $Psi(A) := {Psi(τ) | τ in L_A } subset N^Σ$.

We have that $L_A$ is a *regular language* because it is decide by a finite automata.
Then $Psi(A)$ is a semi-linear set, this means that we can take $u,v_1, dots , v_k$ such that $Psi(A) = u + NN v_1 + dots + NN v_k$ where the $v_i$ vector correspond to the cycle of the automata, then we can easily identify then to express $Psi(A)$ into a know linear decomposition.

So we can easily find if $hat(N)$ is _explainable under A_ or not with a linear programming model, for exemple :

$
  min_(n in NN^r)||hat(N) - (u + sum_(i=1)^r n_i v_i)||
$



In fact, this vector correspond exactly to $E(s)$, i conjecture that for any automata of this forms $A = (Σ,δ,E)$, we have $v$ a vector of size $|S|$ such that $forall s in S, forall e in E(s) space v_s [e] = 1$.


Non pas encore !!

en fait dans mon model, un automate représente une personne, pour consider le jeux c'est à dire alice et bob il faut faire le produit de deux auatomates.


#let lstate = $limits(~, inline: #false)$
Let $A_A = (Σ_A,S_A,lstate_A,E_A)$ and $A_B = (Σ_B,S_B,lstate_B,E_B)$.

The game automata is $A_"AB" = (Σ_A ⊗ Σ_A, S_A ⊗ S_B, lstate_"AB" , E_A union E_B)$.

#todo(position: "inline")[
  Après l'idée c'est de au lieu d'avoir une séquence d'évement, on a une séquence de count N, c'est un quel que sorte un format compressé de nos évement, car en quantique on observe seulement les projections, donc on a envie de retrouver cette idée de visions partielle, mais tout en étant capable de reconstituer les faits !

  Cela serait bien d'arrivé à modéliser cela avec des polynomes ... genre les regles du jeu sont des polynomes, car après on peut faire des thm pour passer des liste de point à des polynomes et des polynomes à des liste de point. C'est vraiment l'idée de, on a des mesures et on veut retrouver la logique, c'est à dire l'interpolation polynomiale.
]

=== Language

#let mip = $sans("MIP")$
#let nexp = $sans("NEXP")$

The class $mip$ is the class of language that can be decide with multiple provers that are not bounded but that can lie, for this reason we have one verifier that can cross chack the answer of multiple provers to convience himself of a global property. This is why $mip = nexp$, because the provers can generate a certificate or a proof of the problem (because there unbounded), but the proof himself is exponentialy long, so if the provers transmit the all proof, the verifier can chack it in exponential time. The goal of the verifier is not just verifier the proof, it can't do this, but verifier that the provers have the proof. The verifier will ask some part of the proof, and check that the ansmer is consistent and the two provers answer the same thing, if it is the case, we can conviece the verifier that the provers have the proof, and then we can decide the language.

So the important point is that the verifier check *localy* the proof, and by doing that, force the existence of a global proof. The true power of $mip$ is the *local* check !

In our case we want a result that say for exemple : If the dynamics of the trace is localy explainable, we can then predict the next and maybe detect some global property about the provers himself. So can have class of language define like that $L = {w | "there exists a hidden global struture such that our prediction accept it"}$

For exemple if the event are localy explainable (this means that this form a path in the representation), can can study the pattern of the path, and them predict a set of possible future event and detect a more general struture.

In the $mip$ class, the provers are non signaling, but suppose that two entity are not communicate is big, if i am a verifier, i am weak, i need also to verifier that the two entity are not communicate. We can do that by detecting deviation in this equality $p(a | x y) = p(a | x y')$. We can imagine two phase : one is the test phase, where the verifier check that the provers respect the rule impose by the game and a second phase where the verifier ask the true question but the provers don't know if we are in the phase 1 or phase 2, so they need to respect the rule in both phase, and if they don't respect the rule in phase 1, we can detect it and reject the language.

=== Count matrix and global structure

Let $N$ the matrix that count the event that come for a give trace $τ$. Let $M_s$ the matrix that has 1 for the event that are in the strategy $s$ and 0 for the other event. We can express $N$ as a combinaison of $M_s$ with some coefficient $c_s$ that represent how many time we see the strategy $s$ in the trace. Then we can define the cone $cal(L) = {sum_s c_s M_s | c_s in NN}$, but this definition in not very good.

Imagine the provers use strategy $s_1$ and we receive the event $e_1$ that correspond to this strategy, the problem is that for 2 players we need 4 different question with the same strategy to be able to record $M_s$. But maybe at the next step, the strategy change to $s_2$ and we don't have a count that is in our cone.

This why i define $cal(P) = {N | exists N^* in cal(L) , N <= N^*}$, that is the set of count that are part of a count that is fully explainable, it is a kind of partial explainability. But the problem with this definition is that all matrix is in $cal(P)$.
#todo(position: "inline")[ceci est encore a réfléchir !]

=== Non signaling condition

$
  N(a | x 0) = N(a | x 1)
  \
  N(b | 0 y) = N(b | 1 y)
  \ =>
  n_(x 1) sum_b N(a b | x 0) = sum_b n_(x 0) N(a b | x 1) quad forall a,x
  \
  n_(0 y) sum_a N(a b | 1 y) = sum_a n_(1 y) N(a b | 0 y) quad forall b,y
$

Si on prend $G = (V,E)$ l'hypergraph qui représente le jeu contextuel, on ajouter des arrêtes qui représente le non signaling.

On alors il faut que pour un noeud $v in V$ on est la propriété :
$
  exists C_v "une constante tel que", forall e in E , v in e => N(e) = C_v
$
Avec $N(e) = sum_(v in e) N_(v)$


=== exemple on $sans("CHSH")$

#let chsh_rule(A, X) = {
  let (a, b) = A
  let (x, y) = X
  if (x, y) == (1, 1) {
    if a != b {
      return true
    } else {
      return false
    }
  } else {
    if a == b {
      return true
    } else {
      return false
    }
  }
}

#tool.draw-nonlocal-game(
  chsh_rule,
  players: 2,
  unit-length: 6em,
  pair-order: ((0, 0), (0, 1), (1, 0), (1, 1)),
  extra-content: {
    import cetz.draw: *

    content((-1, 3.5), $0 |-> 0_(cred(0 I R^0 C_b))$)
    content((-1, 2.5), $0 |-> 1_(cred(1 N R^0 C_q))$)
    content((-1, 1.5), $1 |-> 0_(cred(0 N R^1 C_p))$)
    content((-1, 0.5), $1 |-> 1_(cred(1 I R^1 C_d))$)
    content((0.60, 4.5), $0 |-> 0_(cred(0 I R^0 C_b))$)
    content((1.60, 4.5), $0 |-> 1_(cred(1 N R^0 C_q))$)
    content((2.60, 4.5), $1 |-> 0_(cred(0 N R^1 C_p))$)
    content((3.60, 4.5), $1 |-> 1_(cred(1 I R^1 C_d))$)
  },
)

#v(1cm)

#tool.draw-nonlocal-game(chsh_rule, players: 2, unit-length: 5em, extra-content: {
  import cetz.draw: *

  content((-1, 3.5), $1 |-> 0_(cred(0 "," N))$)
  content((-1, 2.5), $0 |-> 0_(cred(0 "," I))$)
  content((-1, 1.5), $1 |-> 1_(cred(1 "," I))$)
  content((-1, 0.5), $0 |-> 1_(cred(1 "," N))$)
  content((0.60, 4.5), $1 |-> 0_(cred(0 "," N))$)
  content((1.60, 4.5), $0 |-> 0_(cred(0 "," I))$)
  content((2.60, 4.5), $1 |-> 1_(cred(1 "," I))$)
  content((3.60, 4.5), $0 |-> 1_(cred(1 "," N))$)
})

// #cetz.canvas(length: 4em,{
//   import cetz.draw: *

//   let print(aa,bb,arg) = {
//     let x = 0.5 + bb
//     let y = 3.5 - aa
//     content((x,y),arg)
//   }

//   let conv(aa,bb) = {
//     let x = 0.5 + bb
//     let y = 3.5 - aa
//     (x,y)
//   }

//   let cross(aa,bb) = {
//     let x = 0.5 + bb
//     let y = 3.5 - aa
//     content((x,y),text(size: 4em, $crossproduct$))
//   }
//  grid((0,0),(4,4))
//   content((-1,3.5),$1 |-> 0_(cred(0 "," N))$)
//   content((-1,2.5),$0 |-> 0_(cred(0 "," I))$)
//   content((-1,1.5),$1 |-> 1_(cred(1 "," I))$)
//   content((-1,0.5),$0 |-> 1_(cred(1 "," N))$)
//   content((0.60,4.5),$1 |-> 0_(cred(0 "," N))$)
//   content((1.60,4.5),$0 |-> 0_(cred(0 "," I))$)
//   content((2.60,4.5),$1 |-> 1_(cred(1 "," I))$)
//   content((3.60,4.5),$0 |-> 1_(cred(1 "," N))$)
//   let order = ((1,0),(0,0),(1,1),(0,1))
//   for (i, tupleA) in order.enumerate() {
//     let (xx,aa) = tupleA
//     for (j, tupleB) in order.enumerate() {
//       let (yy,bb) = tupleB
//       if chsh_rule(aa,bb,xx,yy) {
//         print(i,j,text(size: 0.8em,$cblue((aa bb | xx yy))$))
//       } else {
//         print(i,j,text(size: 0.8em,$cred((aa bb | xx yy))$))
//       }
//     }
//   }
// })

If the event are localy explainable, they come from a path in the representation, but if the verifier know this, it can trap the provers. Let take for exemple the CHSH game, you can see in the representation that there are two group of valid event, one at the top left corner that is connexe and one at the bottom right corner that is connexe, but there are no path that connect these two group of event, there are two connexe component. But the first component is complete, this means that for any question, there are an event in this group.but the thing is that the group form the following path : $(0 0 | 1 1) , (0 0 | 0 1) , (0 0 | 0 0) , (0 0 | 1 0) , (0 1 | 1 1)$. This means that if we ask the question $(1,1)$, and just after the question $(0,0)$, the provers can't wins, because there need to move two step !

=== GHZ

#let ghz_rule(A, X) = {
  let (a, b, c) = A
  let (x, y, z) = X
  if (x, y, z) == (0, 0, 0) {
    if calc.rem(a + b + c, 2) == 0 {
      return true
    } else {
      return false
    }
  } else if calc.rem(x + y + z, 2) == 0 {
    if calc.rem(a + b + c, 2) == 1 {
      return true
    } else {
      return false
    }
  } else {
    return true
  }
}

#let ghz_promise(A, X) = {
  let (x, y, z) = X
  if calc.rem(x + y + z, 2) == 0 {
    return true
  } else {
    return false
  }
}

#tool.draw-nonlocal-game(ghz_rule, promise: ghz_promise, players: 3, unit-length: 3.5em)

=== C5

#let c5_rule(AA, XX) = {
  let A = array(AA)
  let X = array(XX)

  if X == (1, 1, 1, 1, 1) {
    if calc.rem(A.sum(), 2) == 1 {
      return true
    } else {
      return false
    }
  } else if X.sum() == 1 {
    for (i, val) in X.enumerate() {
      if val == 1 {
        let i_avant = { if i == 0 { 4 } else { i - 1 } }
        let i_apres = { if i == 4 { 0 } else { i + 1 } }
        if calc.rem(A.at(i_avant) + val + A.at(i_apres), 2) == 0 {
          return true
        } else {
          return false
        }
      }
    }
  } else {
    return true
  }
}

#let c5_promise(AA, XX) = {
  let X = array(XX)
  if X == (1, 1, 1, 1, 1) or X.sum() == 1 {
    return true
  } else {
    return false
  }
}

#tool.draw-nonlocal-game(c5_rule, promise: c5_promise, players: 5, unit-length: 1em, label-scale: 1.5)

== Protocol

In the traditionnal model of interactive protocol, we say that we have one verifier and multiple provers and that the provers can cheat on the answer. We also suppose that the provers have some shared ressource but we don't know if they use it or not ? In our case we want to model the malicious behavior of the provers and for that we will suppose that we have two entity that represent the provers, one is the _lab_ that represent the concrete experimentation that is done, this experimentation can't cheat because it is a physical process, and we have the _student_ that will take some ressource from the _verifier_ and carry it to the _lab_, do the experimentation syncronously with the other student and then transmit the result to the verifier. The student can cheat, he can change the ressource, he can change the answer of the lab, he can also change the question that means change the require experimentation protocol. The lab do what the student say.

#let ta(xx) = $limits(xx)^tack.t.short$

We note $x_i$ the question that we give to the _student_ $i$, and we note $a_i$ the answer that the _student_ $i$ give to the _verifier_. We will note $ta(x)$ and $ta(a)$ the true experimentation that the _lab_ does.

Of course the _verifier_ don't know the variable $ta(x)$ and $ta(a)$. But we can reason on it. For exemple know that the local deterministic strategy of the _lab_ is a function $f_i$ that map $f_i (ta(x_i),ta(S_i)) = ta(a_i)$ where $ta(S)$ is the ressource that is potentially modified by the student. We can be a share variable or a quantum state.


= Grille

Disons qu'on se place sur une grille, on a une micro-trace $τ = arrow.t arrow.r arrow.r arrow.r arrow.b arrow.t arrow.r arrow.t$

On fait une observation conjointe sur deux interfaces qui représente Alice et Bob mais on ne sait pas encore si c'est deux personnes : $phi.alt_A = arrow.tr arrow.r dot arrow.tr$ et $phi.alt_B = arrow.r arrow.br arrow.tr arrow.t$ qui représente le délacement de la particule mais vue avec une fréquence d'observation deux fois plus faible, ils voient seulement a distance de deux pas, mais pas forcément avec la meme phase, l'un voit le déplacement $arrow.b arrow.t$ comme $dot$ et l'autre ne voit pas les meme groupes (déphasage de 1) donc voit un déplacement que A de voit pas.

Donc la on peut dire qu'il existe $τ$ tel que $phi.alt_A = Π_A (τ)$ et $phi.alt_B = Π_B (τ)$ c'est à dire qu'on peut expliquer les deux observation par une même micro-trace montrant que les deux observation peuvent être juste une entité ! et pas deux individu différent, bien sur peut-être qu'on a pas de chance et que c'est juste une coincidence...

*Question :* dans cette exemple j'ai utilisé la différence de phase entre les observations mais peut imaginer d'autres choese, des motifs plus complexes, pair ou impair... Après réflexion il faudrait garder l'idée d'une fréquence d'observation et l'idée qu'on ne voit pas quelque chose car on a pas la bonne résulation. Donc le seul changement qu'on pourrait avoir c'est une résolution différente entre A et B et un potentiellement un déphasage.

= Matrice - count - contextuality

On note $k = sum_(a,b,x,y) N(a,b | x,y)$ et $k_(x,y) = sum_(a,b) N(a,b | x,y)$

Prenons l'exemple d'un jeu a deux joueurs, le non signaling impose la condition :
$
  p(a | x 0) = p(a | x 1)
  \
  p(b | 0 y) = p(b | 1 y)
$

Mais nous ne voulons pas de probabilité, nous voulons des nombres, des comptes. On a que :
$
  p(a b | x y) = N(a b | x y) / k_(x y)
$

Donc on peut écrire une contrainte de non signaling sur les comptes :
$
  k_(x 1) N(a | x 0) = k_(x 0) N(a | x 1)
$

=== Hypergraph

La première chose qu'on peut faire c'est de représenter le jeu par un hypergraphe, les noeuds sont les événements $(a b |x y)$ et les hyperarrêtes sont les contraintes du non-signaling et du contexte.

Du fait qu'on a $sum_(a,b) p(a b | x y) = 1$ on dira que les quatres groupes de noeuds $e_(x,y) = {(a b | x y) | a,b in {0,1}}_(x,y)$ sont les hyperarêtes du graphe. En fait pour tout $e in E(G)$ on a $sum_(v in e) p(v) = 1$.

On peut transformer la contraintes :
$
      & N(0 0 | x y) + N(0 1 | x y) + N(1 0 | x y) + N(1 1 | x y) = 1 \
  <=> & N(0 0 | x y) + N(0 1 | x y) + ()
$

On peut voir cela avec trois groupe $A,A'$ et $B$.

On a
$
  N_A + N_A' = k_(A)
  \ k_B N_A' = k_A N_B => N_A' = (k_A / k_B) N_B
$
donc
$
  N_A + (k_A / k_B) N_B = k_A => k_B N_A + k_A N_B = k_A k_B
$
ou en probabilité :
$
  N_A / k_A + N_B / k_B = p_A + p_B = 1
$

Prenons un sommet $v$ par exemple comme intersection de $A$ et $macron(A)$ en position $(1,1)$.

Ce sommet appartient a ces deux contraintes :
$
  N_macron(A) / k_A + N_macron(C)' / k_C = 1
  \
  N_A / k_A + N_(B') / k_B = 1
  \
$

=== Le modéle des comptes est vraiment différent des proba : exemple

prenons cette exemple de configuration de compte :
$
  N = mat(
    3, 1, ., .;
    1, 1, a, b;
    ., ., ., .;
    ., ., ., .;
  )
$
Par la normalisation de l'hyperarrête $e_(0,0)$ on a
$
  p = mat(
    1/2, 1/6, ., .;
    1/6, 1/6, a, b;
    ., ., ., .;
    ., ., ., .;
  )
$

Maintenant on considére l'hyperarrête non signaling qui correspond a la contrainte :
$
  1/2 + 1/6 + a + b = 1
$
La ou avec des probabilités on aurait une infinité de solution, avec les comptes on a une solution unique : $a = 1$ et $b = 1$.

La première chose interessante est que plus notre modéle de probabilité est fins, plus il faut d'évenements au totals.


#proposition[
  Soit $G = (V,E)$ un hypergraphe, et soit $N : V -> NN^*$ un comptage strictement positif. Supposons qu'il existe une famille de constantes $(C_e)_(e in E)$ telle que, pour toute arête $e in E$,
  $
    forall v in e, p(v) = N(v) / C_e
  $
  définisse un modèle valide, c'est-à-dire que
  $
    forall e in E, sum_(v in e) p(v) = 1.
  $
  Si le graphe d'intersection des arêtes de $G$ est connexe, alors il existe une unique constante $C in NN^*$ telle que
  $
    forall e in E, sum_(v in e) N(v) = C.
  $
]

#proof[
  Soit $e in E$. Par hypothèse, pour tout $v in e$,
  $
    p(v) = N(v) / C_e.
  $
  Comme $p$ est un modèle valide, on a
  $
    sum_(v in e) p(v) = 1.
  $
  Donc
  $
    sum_(v in e) N(v) / C_e = 1.
  $
  En factorisant $1 / C_e$, on obtient
  $
    (1 / C_e) sum_(v in e) N(v) = 1,
  $
  d'où
  $
    sum_(v in e) N(v) = C_e.
  $
  Ainsi, pour toute arête $e$, la somme des comptages sur $e$ vaut $C_e$.

  Montrons maintenant que toutes les constantes $C_e$ sont égales. Soient $e,f in E$ telles que
  $
    e inter f != emptyset.
  $
  Soit $v in e inter f$. Alors
  $
    p(v) = N(v) / C_e
    quad text("et") quad
    p(v) = N(v) / C_f.
  $
  Comme $N(v) in NN^*$, on a $N(v) > 0$, donc
  $
    C_e = C_f.
  $

  Le graphe d'intersection des arêtes étant connexe, pour toutes arêtes $e,f in E$, il existe une suite
  $
    e = e_0, e_1, dots, e_k = f
  $
  telle que
  $
    forall i in {0,dots,k-1}, e_i inter e_(i+1) != emptyset.
  $
  Par récurrence sur la chaîne, on obtient
  $
    C_(e_0) = C_(e_1) = dots = C_(e_k).
  $
  Toutes les constantes sont donc égales à une même constante globale, notée $C$.

  Finalement, pour toute arête $e in E$, on a
  $
    sum_(v in e) N(v) = C.
  $

  L'unicité est immédiate. Si $C$ et $C'$ vérifient tous deux
  $
    forall e in E, sum_(v in e) N(v) = C
    quad text("et") quad
    forall e in E, sum_(v in e) N(v) = C',
  $
  alors pour n'importe quelle arête $e$,
  $
    C = sum_(v in e) N(v) = C'.
  $
  Donc $C = C'$.
  $square$
]

#definition[
  On dira que $N : V -> NN^*$ est un *model discret* de parametre de normalisation $k$ (qui est le nombre total d'évenement) du graphe contextuel $G = (V,E)$.
]

Si on note $A$ la matrice d'incidence de $G$, i.e. $A_(e,v) = 1 <=> v in e$.

Alors on dit que $N$ est un modèle discet avec constante de normalisation $C$ si $ A N = C bb(1)_E $

Si on pose $M$ tel que $N = bb(1)_V + M$. On a $A (bb(1)_V + M) = C bb(1)_E$, ce qui implique dans le cas du graph $G = G("CHSH")$ i.e. $A bb(1)_V = 4 bb(1)_E$ que $A M = t bb(1)_E$ avec $t = C - 4$.

Si on définie $p := M/t in RR^V$, alors on a $A p = 1$, c'est à dire $(A p)_e = sum_(v in e) p(v) = 1$. La fonction $p$ correspond a notre model classique.

On a d'ailleurs que le polytope non signaling du jeu CHSH est : $G_"NS" ("CHSH") = {p in RR^V_(>= 0)| A p = 1}$.

Mais dans notre cas, il peut y avoir certains élement de $M$ qui ne sont pas divisible par $t$. Plus précisément, tout élement de $M$ n'a pas forcément comme diviseur commun $t$ si il est différent de 1.

On peux prendre $A$ le jeu CHSH, mais pour généraliser directement pour tout jeu représenter par un graph contextuel avec les contraintes de non signaling et de contextualité (x,y).

Dans notre cas notre ensemble est plutôt :
$
  {m in NN^V | A m = t bb(1) } = t G_"NS" (A) inter ZZ^V
$

Ce sont les points entiers sur une tranche affine du cone.

On peux écrire :
$
  cal(S)_(A) = {(m,t) in NN^V crossproduct NN | A m = t bb(1)}
$
C'est en fait les points entiers du cône :
$
  cal(C)(A) = {(x,t) in RR^V crossproduct RR | A x = t bb(1)}
$

#import "@preview/cetz:0.4.2"

#figure(
  cetz.canvas({
    import cetz.draw: *

    // Style général
    set-style(
      stroke: 0.6pt,
      content: (padding: 2pt),
    )

    // ------------------------------------------------------------------
    // Schéma 3D simplifié du cône
    // ------------------------------------------------------------------

    // Sommets des trois tranches
    let p0 = (0.0, 0.0)

    let a1 = (-2.2, 1.8)
    let b1 = (0.8, 1.8)
    let c1 = (2.2, 3.0)
    let d1 = (-0.8, 3.0)

    let a2 = (-3.1, 3.5)
    let b2 = (1.1, 3.5)
    let c2 = (3.1, 5.1)
    let d2 = (-1.1, 5.1)

    let a3 = (-4.0, 5.3)
    let b3 = (1.4, 5.3)
    let c3 = (4.0, 7.2)
    let d3 = (-1.4, 7.2)

    // Arêtes du cône
    line(p0, a3, stroke: 0.8pt)
    line(p0, b3, stroke: 0.8pt)
    line(p0, c3, stroke: 0.8pt)
    line(p0, d3, stroke: 0.8pt)

    // Tranches t = 1, 2, 3 (en utilisant une liste de points)
    line(a1, b1, c1, d1, close: true, stroke: blue + 0.8pt)
    line(a2, b2, c2, d2, close: true, stroke: blue + 0.8pt)
    line(a3, b3, c3, d3, close: true, stroke: blue + 0.8pt)

    // Marques des niveaux t
    line((-5.0, 0.0), (-5.0, 7.7), mark: (end: ">"))
    content((-5.2, 0.0), anchor: "east", [$t=0$])
    content((-5.2, 2.4), anchor: "east", [$t=1$])
    content((-5.2, 4.3), anchor: "east", [$t=2$])
    content((-5.2, 6.3), anchor: "east", [$t=3$])
    content((-5.0, 8.1), [$t$])

    // Légendes des tranches
    content((4.7, 2.4), anchor: "west", [$G_"NS" ("CHSH")$])
    content((4.9, 4.4), anchor: "west", [$2 G_"NS" ("CHSH")$])
    content((4.9, 6.5), anchor: "west", [$3 G_"NS" ("CHSH")$])

    // Point sommet
    circle(p0, radius: 0.06, fill: black)
    content((0.4, -0.3), [$0$])

    // Points entiers sur les tranches
    let pt-radius = 0.04
    // tranche t = 1
    circle((-1.1, 2.15), radius: pt-radius, fill: black)
    circle((0.0, 2.40), radius: pt-radius, fill: black)
    circle((1.0, 2.65), radius: pt-radius, fill: black)

    // tranche t = 2
    circle((-1.7, 4.05), radius: pt-radius, fill: black)
    circle((-0.4, 4.45), radius: pt-radius, fill: black)
    circle((0.9, 4.80), radius: pt-radius, fill: black)
    circle((1.9, 4.25), radius: pt-radius, fill: black)

    // tranche t = 3
    circle((-2.4, 5.95), radius: pt-radius, fill: black)
    circle((-1.0, 6.30), radius: pt-radius, fill: black)
    circle((0.7, 6.75), radius: pt-radius, fill: black)
    circle((2.3, 6.15), radius: pt-radius, fill: black)
    circle((3.0, 6.65), radius: pt-radius, fill: black)

    // Légende explicative
    circle((5.5, 0.7), radius: pt-radius, fill: black)
    content((5.7, 0.7), anchor: "west", [point entier de $cal(S)$])

    line((5.0, 1.3), (5.5, 1.3), stroke: blue + 0.8pt)
    content((5.7, 1.3), anchor: "west", [section $t$ fixée])

    line((5.0, 1.9), (5.5, 1.9), stroke: 0.8pt)
    content((5.7, 1.9), anchor: "west", [génératrice du cône])

    // Titre
    content((0.0, 8.8), [*Schéma du cône rationnel $cal(C)$ et de son semi-groupe entier $cal(S)$*])
  }),
  caption: [
    Représentation schématique de
    $cal(C) = { (x,t) in RR_(>=0)^16 times RR_(>=0) : A x = t bold(1) }$
    et de
    $cal(S) = cal(C) inter (ZZ^16 times ZZ)$.
    Chaque tranche horizontale $t = "const"$ est un polytope dilaté $t G_"NS"("CHSH")$.
  ],
)

D'après Wikipédia :

Soit un réseau $cal(L)$ de l'espace euclidien $RR^n$ et un polytope $P$ de $RR^n$ dont tous les sommets sont des points du réseau (par exemple, on utilise fréquemment le réseau $cal(L) = ZZ^n$ et des polytopes dont tous les sommets ont des coordonnées entières), engendrant un sous-espace affine de dimension $d$ ($d$ est appelé la dimension de $P$). Pour tout entier positif $t$, soit $t P$ le polytope obtenu par dilatation de $P$ par un facteur $t$, c'est-à-dire le polytope obtenu en multipliant par $t$ les coordonnées de tous les sommets (exprimés dans une base du réseau). Soit $L(P, t) = \# (t P inter cal(L))$ le nombre de points du réseau contenus dans le polytope $t P$. Ehrhart montra en 1962 que $L$ est un polynôme en $t$ de degré $d$, c'est-à-dire qu'il existe des nombres rationnels $L_0(P), dots, L_d (P)$ tels que :
$ L(P, t) = L_d (P) t^d + L_(d-1)(P) t^(d-1) + dots + L_0 (P) $
pour tout entier $t$.

voir @linke2011rationalehrhartquasipolynomials.

Donc en notant $Q_"NS" (t) = \# {t G_"NS" (A) inter Z^V}$ on peut obtenir les coefficients rationnels de ce polynomes !

Mais on peut également généralisé et considéré maintenant le polytope local $L_"loc"$ au lieu de $G_"NS"$ et obtenir la même discrétisation avec le même polynome.

$
  Q_"loc" (t) = \# {t L_"loc" inter Z^V}
$

=== Dans le cas CHSH

Danc ce cas on a que $k = 4 t$ et vu qu'il existe un model discret seulement si $t$ est entier, alors il existe un model discret seulement si $4 | k$, ce qui confirme notre première observation sur $k=1,2,3$

On a également que tout les modeles discret au palier $k=4$ sont locaux, et les non-locaux apparaisse dans le palier $k=8$, on peut voir cela en faisant la différence entre le nombre de modeles discret entre les non-locaux et les locaux grace au polynome de ... .
#proposition[
  Le nombre de modèle discret augmente comme $...$ par rapport à $k$.
]


#todo(position: "inline")[
  Maintenant je veux éthudier plusieurs chose, par exemple c'est quoi la lower bound de k pour avoir tout les modeles à variables caché ? On peut commencer par le non-signaling (c'est simple)
]
=== Non - signaling

On définit $k$ comme le nombre d'évenement reçue, c'est à dire $k = sum_(v in V) N(v) - |V|$ car on commence avec des 1 partouts !

On peut commencer à éthuder le graph de contextualité du CHSH, il a 16 noeuds et 4 hyperarrêtes pour les 4 contextes avec en plus les hyperarrêtes du non signaling.

Pour $k=0$ on a que le modèle $N(v) = 1$ pour tout $v in V$ qui respecte les contraintes du non signaling.

Pour $k=1$ on a un seul $v$ tel que $N(v) = 2$, ce model respecte également les contraintes du non signaling,
mais pour $k=2$ on rencontre notre premier problème, il existe une arrête $e$ qui contient les deux sommet non-un $v_1,v_2$ et on a donc $2 + 2 + 1 + 1 = 6 = C$, mais $v_1$ est contenue également dans une autre arrête $e'$ qui ne contient pas $v_2$, donc on a $2 + 1 +1 +1 = 5 != C$, problème !! idem pour $k=3$.

Pour $k=4$ il y a des models discret possibles.

=== Genérateurs

Voici la gueule des générateurs :
#let local_generators = (
  // D[a0=0,a1=0,b0=0,b1=0]
  ((1, 0, 1, 0), (0, 0, 0, 0), (1, 0, 1, 0), (0, 0, 0, 0)),
  // D[a0=0,a1=0,b0=0,b1=1]
  ((1, 0, 0, 1), (0, 0, 0, 0), (1, 0, 0, 1), (0, 0, 0, 0)),
  // D[a0=0,a1=0,b0=1,b1=0]
  ((0, 1, 1, 0), (0, 0, 0, 0), (0, 1, 1, 0), (0, 0, 0, 0)),
  // D[a0=0,a1=0,b0=1,b1=1]
  ((0, 1, 0, 1), (0, 0, 0, 0), (0, 1, 0, 1), (0, 0, 0, 0)),
  // D[a0=0,a1=1,b0=0,b1=0]
  ((1, 0, 1, 0), (0, 0, 0, 0), (0, 0, 0, 0), (1, 0, 1, 0)),
  // D[a0=0,a1=1,b0=0,b1=1]
  ((1, 0, 0, 1), (0, 0, 0, 0), (0, 0, 0, 0), (1, 0, 0, 1)),
  // D[a0=0,a1=1,b0=1,b1=0]
  ((0, 1, 1, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 1, 1, 0)),
  // D[a0=0,a1=1,b0=1,b1=1]
  ((0, 1, 0, 1), (0, 0, 0, 0), (0, 0, 0, 0), (0, 1, 0, 1)),
  // D[a0=1,a1=0,b0=0,b1=0]
  ((0, 0, 0, 0), (1, 0, 1, 0), (1, 0, 1, 0), (0, 0, 0, 0)),
  // D[a0=1,a1=0,b0=0,b1=1]
  ((0, 0, 0, 0), (1, 0, 0, 1), (1, 0, 0, 1), (0, 0, 0, 0)),
  // D[a0=1,a1=0,b0=1,b1=0]
  ((0, 0, 0, 0), (0, 1, 1, 0), (0, 1, 1, 0), (0, 0, 0, 0)),
  // D[a0=1,a1=0,b0=1,b1=1]
  ((0, 0, 0, 0), (0, 1, 0, 1), (0, 1, 0, 1), (0, 0, 0, 0)),
  // D[a0=1,a1=1,b0=0,b1=0]
  ((0, 0, 0, 0), (1, 0, 1, 0), (0, 0, 0, 0), (1, 0, 1, 0)),
  // D[a0=1,a1=1,b0=0,b1=1]
  ((0, 0, 0, 0), (1, 0, 0, 1), (0, 0, 0, 0), (1, 0, 0, 1)),
  // D[a0=1,a1=1,b0=1,b1=0]
  ((0, 0, 0, 0), (0, 1, 1, 0), (0, 0, 0, 0), (0, 1, 1, 0)),
  // D[a0=1,a1=1,b0=1,b1=1]
  ((0, 0, 0, 0), (0, 1, 0, 1), (0, 0, 0, 0), (0, 1, 0, 1)),
)

#let local_generator_2 = (
  // D[a0=0,a1=0,b0=0,b1=0]
  ((1, 1, 0, 0), (1, 1, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)),
  // D[a0=0,a1=0,b0=0,b1=1]
  ((0, 1, 1, 0), (0, 1, 1, 0), (0, 0, 0, 0), (0, 0, 0, 0)),
  // D[a0=0,a1=0,b0=1,b1=0]
  ((1, 0, 0, 1), (1, 0, 0, 1), (0, 0, 0, 0), (0, 0, 0, 0)),
  // D[a0=0,a1=0,b0=1,b1=1]
  ((0, 0, 1, 1), (0, 0, 1, 1), (0, 0, 0, 0), (0, 0, 0, 0)),
  // D[a0=0,a1=1,b0=0,b1=0]
  ((0, 0, 0, 0), (1, 1, 0, 0), (1, 1, 0, 0), (0, 0, 0, 0)),
  // D[a0=0,a1=1,b0=0,b1=1]
  ((0, 0, 0, 0), (0, 1, 1, 0), (0, 1, 1, 0), (0, 0, 0, 0)),
  // D[a0=0,a1=1,b0=1,b1=0]
  ((0, 0, 0, 0), (1, 0, 0, 1), (1, 0, 0, 1), (0, 0, 0, 0)),
  // D[a0=0,a1=1,b0=1,b1=1]
  ((0, 0, 0, 0), (0, 0, 1, 1), (0, 0, 1, 1), (0, 0, 0, 0)),
  // D[a0=1,a1=0,b0=0,b1=0]
  ((1, 1, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (1, 1, 0, 0)),
  // D[a0=1,a1=0,b0=0,b1=1]
  ((0, 1, 1, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 1, 1, 0)),
  // D[a0=1,a1=0,b0=1,b1=0]
  ((1, 0, 0, 1), (0, 0, 0, 0), (0, 0, 0, 0), (1, 0, 0, 1)),
  // D[a0=1,a1=0,b0=1,b1=1]
  ((0, 0, 1, 1), (0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 1, 1)),
  // D[a0=1,a1=1,b0=0,b1=0]
  ((0, 0, 0, 0), (0, 0, 0, 0), (1, 1, 0, 0), (1, 1, 0, 0)),
  // D[a0=1,a1=1,b0=0,b1=1]
  ((0, 0, 0, 0), (0, 0, 0, 0), (0, 1, 1, 0), (0, 1, 1, 0)),
  // D[a0=1,a1=1,b0=1,b1=0]
  ((0, 0, 0, 0), (0, 0, 0, 0), (1, 0, 0, 1), (1, 0, 0, 1)),
  // D[a0=1,a1=1,b0=1,b1=1]
  ((0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 1, 1), (0, 0, 1, 1)),
)

#let pr_generators_2 = (
  // PR[alpha=0,beta=0,gamma=0]
  ((0, 1, 1, 0), (1, 1, 0, 0), (1, 0, 0, 1), (0, 0, 1, 1)),
  // PR[alpha=0,beta=0,gamma=1]
  ((1, 0, 0, 1), (0, 0, 1, 1), (0, 1, 1, 0), (1, 1, 0, 0)),
  // PR[alpha=0,beta=1,gamma=0]
  ((1, 1, 0, 0), (0, 1, 1, 0), (0, 0, 1, 1), (1, 0, 0, 1)),
  // PR[alpha=0,beta=1,gamma=1]
  ((0, 0, 1, 1), (1, 0, 0, 1), (1, 1, 0, 0), (0, 1, 1, 0)),
  // PR[alpha=1,beta=0,gamma=0]
  ((1, 0, 0, 1), (1, 1, 0, 0), (0, 1, 1, 0), (0, 0, 1, 1)),
  // PR[alpha=1,beta=0,gamma=1]
  ((0, 1, 1, 0), (0, 0, 1, 1), (1, 0, 0, 1), (1, 1, 0, 0)),
  // PR[alpha=1,beta=1,gamma=0]
  ((0, 0, 1, 1), (0, 1, 1, 0), (1, 1, 0, 0), (1, 0, 0, 1)),
  // PR[alpha=1,beta=1,gamma=1]
  ((1, 1, 0, 0), (1, 0, 0, 1), (0, 0, 1, 1), (0, 1, 1, 0)),
)

#let pr_generators = (
  // PR[alpha=0,beta=0,gamma=0]
  ((1, 0, 1, 0), (0, 1, 0, 1), (1, 0, 0, 1), (0, 1, 1, 0)),
  // PR[alpha=0,beta=0,gamma=1]
  ((0, 1, 0, 1), (1, 0, 1, 0), (0, 1, 1, 0), (1, 0, 0, 1)),
  // PR[alpha=0,beta=1,gamma=0]
  ((1, 0, 0, 1), (0, 1, 1, 0), (1, 0, 1, 0), (0, 1, 0, 1)),
  // PR[alpha=0,beta=1,gamma=1]
  ((0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 0, 1), (1, 0, 1, 0)),
  // PR[alpha=1,beta=0,gamma=0]
  ((1, 0, 1, 0), (0, 1, 0, 1), (0, 1, 1, 0), (1, 0, 0, 1)),
  // PR[alpha=1,beta=0,gamma=1]
  ((0, 1, 0, 1), (1, 0, 1, 0), (1, 0, 0, 1), (0, 1, 1, 0)),
  // PR[alpha=1,beta=1,gamma=0]
  ((1, 0, 0, 1), (0, 1, 1, 0), (0, 1, 0, 1), (1, 0, 1, 0)),
  // PR[alpha=1,beta=1,gamma=1]
  ((0, 1, 1, 0), (1, 0, 0, 1), (1, 0, 1, 0), (0, 1, 0, 1)),
)

#table(
  columns: (1fr, 1fr, 1fr, 1fr),
  align: center + horizon,
  stroke: none, // Pas de bordures pour un look plus minimaliste
  ..local_generators
    .enumerate()
    .map(((i, vec)) => [
      #set text(0.8em, gray)
      $mat(..vec)$
    ])
)

pr generators

#table(
  columns: (1fr, 1fr, 1fr, 1fr),
  align: center + horizon,
  stroke: none, // Pas de bordures pour un look plus minimaliste
  ..pr_generators
    .enumerate()
    .map(((i, vec)) => [
      #set text(0.8em, gray)
      $mat(..vec)$
    ])
)

==== Better ordering !

Ordering :
$1 |-> 0 ; 0 |-> 0 ; 1 |-> 1 ; 0 |-> 1$

#table(
  columns: (1fr, 1fr, 1fr, 1fr),
  align: center + horizon,
  stroke: none, // Pas de bordures pour un look plus minimaliste
  ..local_generator_2
    .enumerate()
    .map(((i, vec)) => [
      #set text(0.8em, gray)
      $mat(..vec)$
    ])
)

pr generators

#table(
  columns: (1fr, 1fr, 1fr, 1fr),
  align: center + horizon,
  stroke: none, // Pas de bordures pour un look plus minimaliste
  ..pr_generators_2
    .enumerate()
    .map(((i, vec)) => [
      #set text(0.8em, gray)
      $mat(..vec)$
    ])
)

=== Observations

Maintenant dans notre modéle, on va dire qu'on a une obeservation $tilde(N)$ de parametre $k = N_"tot" - 16$. Le but est d'arriver à caratériser cette observation, est-ce que Alice et Bob communique, ou plutôt à quel niveau de confiance on peut dire que Alice et Bob communique ? Au lieu de regarder seulement le model discret, on va imaginer sa contruction, son histoire pour arriver à cette observation, c'est à dire les différentes étape de l'observation, ce sont en fait la séquence de +1 qui ont été ajouté pour arriver à l'observation $tilde(N)$. On notera cela $τ = e_1 dots e_k$ une trace de $tilde(N)$.

Dans un peut vouloir dire qu'on veut essayer d'expliquer $tilde(N)$ seulement avec une trace completement non - signaling, c'est à dire ou chaque model partielle $tilde(N)_t = sum_(s=1)^t e_s$ est un model disret de notre graph contextuel $G$. On peut interpréter $e_i$ comme un évenement $e_i = (a b | x y)$ dans le cas Alice et Bob ou bien simplement comme un noeuds qui arrive.

#let MM = $cal("M")$

On note l'ensemble des models discret de parametre $k$ du graph $G$ comme $MM(G, k) = {N : V -> NN^* | exists C, forall e in E, N(e) = C " et " N(V) = k - |V|}$

Dans tout la suite on se place dans un graph de contextualité $G$ de préference celui du CHSH.

On définit la norme NS comme :
$ ||N||_"ns" = min_(k in NN\ M in MM(G, k)) ||M - N||_1 $

Bien sûr si $k(N) = 3$ et $MM(G, 3) = emptyset$ on a forcément $||N||_"ns" > 0$, mais si $MM(G, k) != emptyset$ on a pas forcément $||N||_"ns" = 0$ !

On définit également :
$
  B(N) = min_("trace" τ=e_1 dots e_k "de" N) (max_(1 <= t <= k) ||N_t := sum_(s = 1)^t e_s ||_"ns")
$
avec $B(N,τ) := (max_(1 <= t <= k) ||N_t := sum_(s = 1)^t e_s ||_"ns")$ qui représent l'éloignement le plus grand atteint durant la construction de $N$ par rapport a un model discret non signaling.

Cette définition prend son sens car défois durant le precessus il nous est parfais obligé de passé pas des étapes qui nous semble non-signaling, mais si au final, on s'en écarte jamais trop, cela nous reconforte dans le fait que cela est peut-être qu'une coincidence.

#todo(
  position: "inline",
)[La prochaine étape est donc d'étudier les matrices N avec des B(N) différent, on commence par B(N) = 0
  Il faudrait également étudier le cas particulier des models à variables caché !
]

=== Between past and future !

Maintenant on veut étudier la relation entre une obseration $tilde(N)$ de parametre $k$ et les chemins qui peuvent expliquer cette observation, c'est à dire les différentes traces $τ$ entre le passé et le futur (modeles discret).

On définit : $ cal(H)[(m_1,t_1),(m_2,t_2)] := {τ = e_1 dots e_n | m_1 + sum_(i=1)^n e_i = m_2 and t_1 + n = t_2} $

Cela représente l'ensemble des traces qui permettent de passer d'un modèle discret $m_1$ à un modèle discret $m_2$.
Je le note $cal(H)$ car dans notre cadre philosophique, on interprète les chemins compatibles entre un passé et un futur comme les histoires possibles compatibles, on dit que nous vivons dans une superposition de ces histoires pour faire l'analogie avec le quantique.

On peut voir également les choses comme ceci :
$
  cal(H)[(m_2 - m_1, t_2 - t_1)] = cal(H)[(m,t)] = {τ = e_1 dots e_n | sum_(i=1)^n e_i = m and n = t}
$

Soit $tilde(m) in NN^V$ un comptage. Le but est de ratacher cette observation à notre histoire qu'on se fait du monde. Imaginons que nous aimerons que Alice et Bob soient non signaling, alors on peut se demander comment relier notre observation a notre idée actuel du monde c'est à dire les modeles discrets.

Prenons quelques exemple :

Si $k(tilde(m)) = 1$, alors cette observation est a une distance de 1 du modele discret d'avant, c'est à dire $m = 0$, et a distance 3 du modele discret d'après, c'est à dire $m=4$.

$
  N^- (tilde(m)) := min_(m in MM(G, 0)\ m <= tilde(m)) ||tilde(m) - m||_1 = 1 \
  N^+ (tilde(m)) := min_(m in MM(G, 4)\ m >= tilde(m)) ||tilde(m) - m||_1 = 3
$

La première question est la suivante :
- Est-ce que $N^-$ et $N^+$ dépend uniquement de $k(tilde(m))$ ? peut-on toujours trouver un modèle discret en rajoutant et enlevant des évenements de notre observation ? J'ai vraiment envie de dire que $N^- (tilde(m)) = k(tilde(m)) mod 4$

La réponse est non !

déjà :

$
  N^- (tilde(m)) = k(tilde(m)) - max_(m in cal(M)(4t) \ m <= tilde(m)) k(m) = k(tilde(m)) - 4 r^- (tilde(m))\
  N^+ (tilde(m)) = min_(m in cal(M)(4t) \ m >= tilde(m)) k(m) - k(tilde(m)) = 4 r^+ (tilde(m)) - k(tilde(m))
$
Donc on peut se ramener à étudier ceci :
$
  r^- (tilde(m)) := {t | exists m in cal(S)(t) , m <= tilde(m)}\
  r^+ (tilde(m)) := {t | exists m in cal(S)(t) , m >= tilde(m)}
$

Avec $cal(S)(t) = {m | (m,t) in cal(S)}$

Grace a notre base de Hilbert, on a que pour tout $(m,t) in cal(S)$ :
$
  m = sum_i α_i d_i + sum_i β_i p_i\
  t = sum_i α_i + 2 sum_i β_i
$

On note $H := (d_1, dots, d_16, p_1, dots , p_8)$ et $w := (1, dots, 1,2, dots, 2)$.

Donc on a :
$
  r^- (tilde(m)) = max_(x in NN^24) {w dot x | H x <= tilde(m)} \
  r^+ (tilde(m)) = min_(x in NN^24) {w dot x | H x >= tilde(m)}
$

C'est en fait un problème d'optimisation linéaire en nombre entier !
$
  R^- (tilde(m)) = {w dot x | H x <= tilde(m) , x in NN^24}\
  R^+ (tilde(m)) = {w dot x | H x >= tilde(m) , x in NN^24}
$

#definition[
  Soit $S subset NN$ un semi-groupe additif commutatif. Un *idéal additif* de $S$ est une partie non vide $I subset S$ telle que
  $
    I + S subset I,
  $
  c'est-à-dire telle que, pour tout $a in I$ et tout $s in S$, on ait $a+s in I$.
]

Introduisons le semi-groupe des degrés
$
  S_w := { w dot x | x in NN^24 }.
$
Dans CHSH, comme les générateurs déterministes ont poids $1$ et les générateurs PR ont poids $2$, on a
$
  S_w = {a + 2 b : a,b in NN} = NN.
$

#proposition[
  Pour toute observation $tilde(m) in NN^16$, l'ensemble
  $
    R^+ (tilde(m)) = { w dot x | H x >= tilde(m), x in NN^24 }
  $
  est un idéal additif du semi-groupe $S_w$.
]

#proof[
  L'ensemble $R^+ (tilde(m))$ est non vide. En effet, en additionnant un nombre suffisamment grand de générateurs déterministes, on obtient toujours un vecteur $H x$ qui domine coordonnée par coordonnée l'observation $tilde(m)$.

  Soient maintenant $t in R^+ (tilde(m))$ et $s in S_w$. Par définition, il existe $x,u in NN^24$ tels que
  $
    t = w dot x, quad s = w dot u,
  $
  avec
  $
    H x >= tilde(m).
  $
  Alors
  $
    H(x+u) = H x + H u >= H x >= tilde(m),
  $
  donc $x+u$ est encore faisable. De plus,
  $
    w dot (x+u) = w dot x + w dot u = t+s.
  $
  Ainsi $t+s in R^+ (tilde(m))$. On a donc
  $
    R^+ (tilde(m)) + S_w subset R^+ (tilde(m)),
  $
  ce qui prouve que $R^+ (tilde(m))$ est un idéal additif de $S_w$.
  $square$
]

Dans CHSH, cette propriété implique immédiatement que l'ensemble des degrés faisables au-dessus de $tilde(m)$ est un intervalle de $NN$ à partir de son minimum.

#proposition[
  Pour toute observation $tilde(m) in NN^16$, on a
  $
    R^+ (tilde(m)) = r^+ (tilde(m)) + NN.
  $
]

#proof[
  D'après la proposition précédente, $R^+ (tilde(m))$ est un idéal additif non vide de $NN$. Posons
  $
    r^+ (tilde(m)) := min R^+ (tilde(m)).
  $
  Comme $r^+ (tilde(m)) in R^+ (tilde(m))$ et comme $R^+ (tilde(m))$ est un idéal, on obtient
  $
    r^+ (tilde(m)) + NN subset R^+ (tilde(m)).
  $

  Réciproquement, si $t in R^+ (tilde(m))$, alors par minimalité de $r^+ (tilde(m))$ on a $t >= r^+ (tilde(m))$, donc il existe $n in NN$ tel que
  $
    t = r^+ (tilde(m)) + n.
  $
  Ainsi $t in r^+ (tilde(m)) + NN$, ce qui montre
  $
    R^+ (tilde(m)) subset r^+ (tilde(m)) + NN.
  $
  Les deux inclusions donnent l'égalité annoncée.
  $square$
]

Autrement dit, une fois connu le plus petit degré réalisable $r^+ (tilde(m))$, tous les degrés supérieurs sont automatiquement réalisables. L'ensemble $R^+ (tilde(m))$ ne contient donc pas d'information plus fine que son minimum.

En revanche, l'ensemble
$
  R^- (tilde(m)) = {w dot x | H x <= tilde(m), x in NN^24}
$
est borné supérieurement, donc fini en général. Ce n'est pas un idéal additif ; l'objet naturel à étudier de ce côté est son maximum, c'est-à-dire $r^- (tilde(m))$.

=== Lower bound de $r (tilde(m))$ et Benders decomposition

On peut définir la version relaxé de notre problème :
$
  r_"rel"^- (tilde(m)) = max {w dot x | H x <= tilde(m), x in RR^24_(>=0)}\
  r_"rel"^+ (tilde(m)) = min {w dot x | H x >= tilde(m), x in RR^24_(>=0)}
$
En écrivant le dual on a :
$
  r_"rel"^- (tilde(m)) = min {tilde(m) dot y | y in Y}\
  "avec" Y = {y in RR^16_(>=0) | H^T y >= w}
$

On obtient donc un problème d'optimisation linéaire sur un polytope fixe, on peut donc faire une benders décomposition pour trouver des cuts de notre polytope $Y$ qui nous permettent d'obtenir une meilleure lower bound de $r^- (tilde(m))$.

L'idée géométrique de la décomposition de Benders est la suivante : la fonction
$
  f(tilde(m)) := r_"rel"^- (tilde(m)) = min_(y in Y) tilde(m) dot y
$
est la borne inférieure d'une famille de formes linéaires. Elle est donc concave, affine par morceaux, et chaque solution duale optimale $y^(t) in Y$ en un point $tilde(m)^(t)$ fournit un hyperplan de support.

Plus précisément, si $y^(t)$ est dual optimal pour l'instance $tilde(m)^(t)$, alors pour toute observation $tilde(m)$ on a
$
  f(tilde(m)) <= tilde(m) dot y^(t)
  = f(tilde(m)^(t)) + y^(t) dot (tilde(m) - tilde(m)^(t)).
$
Autrement dit, $y^(t)$ joue le rôle d'un sous-gradient de $f$ en $tilde(m)^(t)$, et l'inégalité
$
  eta <= f(tilde(m)^(t)) + y^(t) dot (tilde(m) - tilde(m)^(t))
$
est une *coupe de Benders* valable pour l'épigraphe inversé de la fonction concave $f$.

#figure(
  cetz.canvas({
    import cetz.draw: *

    set-style(
      stroke: 0.7pt,
      content: (padding: 2pt),
    )

    let a = (0.0, 0.0)
    let x0 = 3.4

    line((0, 0), (7.0, 0), mark: (end: ">"))
    line((0, 0), (0, 4.5), mark: (end: ">"))

    content((7.15, -0.05), [$tilde(m)$])
    content((-0.1, 4.65), [$eta$])

    line((0.7, 3.7), (2.0, 2.2), stroke: blue + 1.2pt)
    line((2.0, 2.2), (3.4, 1.45), stroke: blue + 1.2pt)
    line((3.4, 1.45), (4.9, 1.7), stroke: blue + 1.2pt)
    line((4.9, 1.7), (6.4, 2.75), stroke: blue + 1.2pt)
    content((6.25, 3.0), text(blue)[$
      f(tilde(m)) = r_"rel"^- (tilde(m))
    $])

    line((x0, 0), (x0, 1.45), stroke: gray + 0.6pt, dash: "dashed")
    circle((x0, 1.45), radius: 0.06, fill: black)
    content((x0, -0.35), [$tilde(m)^(t)$])

    line((0.5, 2.32), (6.6, 0.49), stroke: red + 1pt)
    content((5.95, 0.25), text(red)[Benders cut])
  }),
  caption: [Vue géométrique : une solution duale optimale en $tilde(m)^(t)$ définit une coupe affine qui majore la fonction $f(tilde(m)) = r_"rel"^- (tilde(m))$.],
)

Dans notre cadre, cela signifie qu'à chaque itération on choisit une observation de référence $tilde(m)^(t)$, on résout le dual
$
  min {tilde(m)^(t) dot y | y in Y},
$
puis on ajoute au problème maître la coupe
$
  eta <= tilde(m) dot y^(t).
$
En accumulant ces coupes, on obtient une approximation polyédrale de plus en plus fine de la fonction $tilde(m) mapsto r_"rel"^- (tilde(m))$, et donc des bornes inférieures de plus en plus précises pour $r^- (tilde(m))$.

=== Wining probability

Quand on parle d'une matrice de comptage $N$, on parle en fait d'un batch d'évenement. L'observateur ne voient pas l'ordre interne, mais seulement en version comprimé ou on a perdu l'ordre. On peut avoir plusieurs batch ${N_t}_(t in NN^*)$ et on dira pour commencer que le nombre d'évenement par batch est le même : $k(N_t) = k$.

On définit $N_T := sum_(i=1)^T N_t$ de masse $T k$.

On définit le gain de batch $t$ : $ w_t := sum_(e in V) underbrace(bb(v)(e), in {0,1}) N_t (e) = bb(v)^T N_t $
et donc le gain accumulé : $w_T := sum_t w_t in NN$.

En fixant un seuil $q =r/s$, on dit que le gain est supérieur à un seuil $q$ si $s w_T >= r k(N_T) = r T k$. On dit que le gain est de $q$ si $s w_T = r T k$,(i.e. $q = w_T/k(N_T)$).

=== Application au cas CHSH

Pour rappel : $N = bb(1) + m$ avec dans le cas d'une stratégie deterministe $m = D λ$ avec $D = (d_1,dots,d_16)$ la bases déterministes et $λ in NN^16$.

Pour rappel on a $A N = C bb(1)$ et $A m = t bb(1)$ avec $t = C - 4$.

Donc $w_t = bb(v)^T N_t = bb(v)^T (bb(1) + D λ) = 8 + sum_i (bb(v)^T d_i ) λ_i$

On observe que $bb(v)^T d_i in {1,3}$ et que le nombre de 1 est le même que le nombre de 3.
Donc $sum_i (bb(v)^T d_i ) λ_i = sum_(i=1)^8 1 λ_i + sum_(i=9)^16 3 λ_i$

Plus généralement on note $A := {i | bb(v)^T d_i = 1}$ et $B := {i | bb(v)^T d_i = 3}$ et $λ_A := sum_(i in A) λ_i$ et $λ_B := sum_(i in B) λ_i$.

Donc $w_t (N_t) = 8 + λ_A + 3 λ_B$ avec $k(N_t) = 16 + 4(λ_A + λ_B)$.

On définit la probabilité de gain par $sup_(λ_A,λ_B) w_t/(k(N_t))$

On peut vérifier facilement que le gain maximum est atteint pour un seuil de $3/4$. On calcule $4 (8 + λ_A + 3 λ_B) - 3 (16 + 4(λ_A + λ_B)) = -16 - 8 λ_A$. Donc même avec $λ_A$ le gain de seuil $3/4$ n'est jamais atteint, et cela au du au fait que l'on rajoute un fond uniforme de 1 partout, sinon avec $λ_A = 0$ cette égalité serait nulle.

Avec un seuil de $1/2$ on aurait :
$
  2 (8 + λ_A + 3 λ_B) - 1 (16 + 4(λ_A + λ_B)) = -2 λ_A + 2 λ_B = 2 (λ_B - λ_A)
$

Plus généralement, on cherche $q^* := sup_{a,b : a+b=t} f(a,b) := (8 + a + 3b)/(16 + 4(a + b))$. Mais concrétement on a une série de comptage $N_t$ avec leurs $λ^A_t,λ^B_t$ qu'on notera $a_t,b_t$. On dira que les batchs ${N_t}_(t in [T])$ ont un gain asymptotique de $q$ si quand $t -> infinity$ on a $f(a_t,b_t) -> q$.

Le truc est que $t$ est fixé ! Il vaut $4 t = k$ qui est de même taille pour chaque batch.

Donc $q^*_t := sup_(a,b : a + b = t) = 3/4 -1/(t+4) = 3/4 - 1/C$.

Pour faire plus simple, on peut simplement supprimer le fond uniforme et dire que $q^*_t = 3/4$.

Vu qu'on a fixé la granularité de notre modèle discret à $k = 4 t$ on a que la meilleurs stratégie de peux faire mieux que $q^*_t$.

== 1er version du model explicatif concurentiel

Let start by the result of a experimentation $tilde(m)$. We want to explain this experiment. Traditionnaly we explain this result by defining a model that we call $H$, and by showing that this result is close to the model. But by doing that we forget the intermediate observation the lab does when he do the experiment, in a lot of experimentation, we repeat a measure that produce a observation, we put all this result in a graph and we check that the model interpolate closely the result ! If we want to be precise we can also precise the number of point and saying that we are sure about ?? that the model fit with the experimentation. The goal is, instead of staticly comparing the result with a model, we want to re construct the history of the result by a sequence of event (trace) and study dynamically each step by comporing it with the model, and checking for exemple that the tolerance between the experimentation and the model will be controlled by an asymptotic bound $β_n = 1/n$ for exemple instead of a fixed $β$.

In the previous section we defined the notion of $N^- (tilde(m))$ and $N^+ (tilde(m))$ as the distance of the observation $tilde(m)$ to the nearest model discret below and above. But this is not enough, because we see that the intermidiate observation can be very far from the model. We need a finer tool to control this.

This is the goal of the automata. We will assume that we can decompose each model hypergraph $H$ into a basis of generator. Let define the generator automaton that will produce the following generator trace. So at any step we can say that we are in ...
All of this to define the notion of open and close automata ... we have that $N_t =sum_(g in C_t) g + sum_((g,f) in O_t) f$.


... (explain all the following !)

The idea is instead of saying, we have a model (a set of feasible probability distribution) and we note the wining probability the maximum of the gain function on this model, i want to say that the gain is the model ! This means that we hope that the observation will converge to it.
We define the cost of using PR generator, and we want to study how many it will cost us to reach the quantum gain with for exemple the controle bound of $β_n$. This can permit us to understand better the quantum gain, because a all branch of reseach want to understand or build a model that with a list of axiome, or by cuting the polytope of non signaling catch quantum behavior !

== ?

Une interface est une donnée cachée intermédiaire, plus fine que le phénomène visible mais plus grossière que la micro-trace complète, qui conserve exactement l’information nécessaire pour :

- raccorder un passé à un futur,
- comparer plusieurs projections locales,
- exprimer la synchronisation, la phase ou la résolution d’un environnement.



#bibliography("refs.bib")
