#import "../template.typ": book, corollary, definition, example, lemma, proof, proposition, remark
#import "../prelude.typ": *

= Conclusion

This report started from a simple methodological choice: before normalizing a probability table, keep the integer counts. This choice is not a rejection of the probabilistic formalism. It is a way to preserve information that normalization erases: the level at which an observation was obtained, the arithmetic constraints imposed by finite repetition, and the possibility of viewing an observation as a partial process that may still be completed.

The first contribution is the translation itself. By replacing probabilities with integer counts, contextuality becomes a question about integer decomposition in an affine semigroup. The Hilbert basis of the compatible semigroup gives the elementary bricks of explanation. In the $(2,2,2)$ Bell scenario, these bricks are the local deterministic generators and the lifted PR generators. The Ehrhart and quasi-Ehrhart polynomials count how many integer models exist at each level. This is a change of perspective: instead of asking whether a point lies in a convex hull, we ask how an integer vector decomposes into irreducible generators.

The second contribution is the automaton model. A generator is treated as an elementary process that can be produced step by step. An interrupted experiment is represented by a dynamic state: a collection of closed copies and open copies, each with a residual part that records what remains to be emitted. This turns partial observations into meaningful mathematical objects. A prefix is not an error; it is the visible past of a process that still has a future. The transition condition between states preserves the identity of each generator and allows its residual to decrease. This is a modelling choice, but a natural one: it captures the idea that an elementary process may continue, but it cannot become another process.

The third contribution is the finite-level Tsirelson bound $T(t)$. At each level $t$, the best quantum-realizable integer CHSH score is a rational number. The celebrated value $2 sqrt(2)$ is not a parameter of the discrete model; it is an asymptotic idealization that no finite experiment can reach. The gap is controlled by the Diophantine properties of $sqrt(2)$. Crucially, this operational bound can be approximated using the same tools as the standard approach: the NPA hierarchy gives outer approximations of the quantum set, and these approximations translate directly into integer linear programs. The integer framework does not replace the standard quantum relaxations; it reuses them while keeping the finite-level structure.

The fourth contribution is the recovery of the contextual fraction. The past distance $D^-(N)$ measures how much of a compatible counting can be explained by a non-contextual mechanism. After normalization, this distance recovers exactly the contextual fraction of @Abramsky_Barbosa_Mansfield_2016. The dynamic framework therefore agrees with the standard sheaf-theoretic measure on its static coordinate. But it also carries more information: the completion deficit $D^(arrow.loop)(N)$ measures how much work remains to close a partial explanation, and the interruption profile $k_η$ records, for each coordinate, its temporal position in the process. These objects have no analogue in the probabilistic framework.

The fifth contribution is the exploration of dynamic constraints. Several candidate constraints were tested on concrete examples. Scalar constraints, such as the product $d_η^- d_η^+$, detect non-classicality but do not isolate the quantum region. This observation points toward finer objects. The interruption profile breaks the compression imposed by scalar distances: it remembers how the interruption is distributed across coordinates, not only how much has been emitted and how much remains. Constraints on the profile can express synchronization conditions, emission orderings, and dispersion bounds that are invisible to any scalar measure. The constraint-programming formulation makes these computations explicit.

The work presented here is exploratory. It does not claim to have found a dynamic theory that characterizes quantum phenomena. What it has done is build a language in which such a question can be posed precisely. The framework is constructive: it starts from finite observations, keeps the integer structure, and defines dynamic objects that record how a process is produced, interrupted, and completed. It is compatible with existing tools: the NPA hierarchy, the contextual fraction, and the sheaf-theoretic formulation all have natural translations into this language.

This opens a dimension of contextuality that has not yet been explored. By passing from a static description, where an empirical model is a point in a polytope, to a dynamic description, where it is the visible trace of an interruptible process, a whole field of experimentation becomes accessible. Which constraints on the interruption profile isolate the quantum region? How does the profile behave in scenarios more complex than CHSH? Can a theory be built that revises its own explanatory criteria during the experiment? These are concrete questions that the framework makes testable. The door is open for passing from a contextuality classified by static properties to a contextuality understood through its dynamics of production, interruption, and completion.
