#import "../template.typ": book, corollary, definition, lemma, proof, proposition, remark
#import "../prelude.typ": *

= Context and Motivation <chap:context-motivation>

== Why start from observation?

Scientific theories do not begin with reality given all at once. They begin with phenomena: outcomes, traces, correlations, and reports produced through concrete experimental interfaces. A hidden variable, a state, a Hilbert space vector, or an automaton is therefore not direct access to reality itself. It is a model introduced to organize what is observed.
This distinction is modest, but it is important for the rest of the report. We do not try to reveal a final hidden world. We ask which hidden structures can explain the visible data, how much structure they require, and what they still fail to explain. In that sense, the word *model* should be read operationally. A model is a disciplined way of connecting observed phenomena to a possible hidden organization.
This position is not meant to weaken science. On the contrary, it makes the task more precise. Since the hidden structure is not directly given, it must be reconstructed under constraints. It must fit the observations, respect the operational limitations of the experiment, and use a controlled amount of structure. A model is then judged by its explanatory power, and by its coherence.

== Truth, understanding, and interruption

In this report, truth is used in an operational and provisional sense. A model is accepted when it is the best available explanation of the observed phenomena. If the observations change, or if the class of admissible models changes, the accepted model may change as well. This does not make truth arbitrary. The choice of a model is constrained by data, by mathematical consistency, and by the cost of the hidden resources used in the explanation.

Understanding is slightly different. A model may give correct predictions while remaining too opaque to reuse. Here, a model is understood when it can be compressed, transmitted, interrupted, and reconstructed without losing its explanatory role.

A simple analogy is curve fitting. Suppose that an experiment produces a sequence of points $(x_i,y_i)$. In a classical analysis, one may fix a class of models, for instance polynomials of degree at most $3$, and choose the polynomial that best fits the first $n$ points:
One then says that the model is good if the final error is small enough.
This report asks for a more dynamic requirement. The explanation procedure itself should be observable and interruptible. After each new point, we obtain a new model, a new error, and a transition from the model at step $n$ to the model at step $n+1$. A good explanatory process should not only end with a small error. Its successive updates should also follow a coherent pattern.
This is the sense in which we want a kind of meta-model. We do not only want a final explanation of the completed experiment. We also want to track the history of partial explanations, their errors, and their possible continuations. If the experiment is interrupted at time $n$, the current state should still have a meaning.

This point will become central later. A probability table is a completed summary. It has already forgotten the order of events, the number of occurrences before normalization, and the possible unfinished mechanisms that produced the data. If our aim is only prediction, this loss may be acceptable. If our aim is reconstruction, it is too strong. We need a language that keeps enough information to restart the process after an interruption.

The report therefore takes seriously a simple methodological principle: before normalizing, count; before completing, keep the prefix; before replacing a mechanism by a probability distribution, ask what hidden process could have produced it.

== Existing routes toward the quantum model

The question of which model best explains quantum phenomena is not new. Bell's theorem showed that local hidden-variable models cannot reproduce all quantum predictions @Bell_1964. The CHSH inequality gave a particularly clear experimental and mathematical form of this obstruction @Clauser_Horne_Shimony_Holt_1969. These results changed the status of hidden mechanisms: the difficulty is not merely that the hidden variables are unknown, but that some families of local observations cannot be glued into a single classical global assignment.

Several lines of work explore whether general operational principles can characterize quantum theory, for instance through generalized probabilistic theories @Barrett_2007 or axiomatic reconstructions @Hardy_2001 @Chiribella_DAriano_Perinotti_2011 @Masanes_Muller_2011. These works illustrate a difficulty: if the axioms are too weak, one obtains theories larger than quantum theory; if they are too strong, the reconstruction may simply hide the quantum structure inside the assumptions.

The same difficulty appears from another direction in the resource-theoretic work of @Ansanelli_etal_2026. A #emph[resource theory] does not study physical systems only as isolated objects. It asks which transformations are possible when one restricts the allowed operations. In the deterministic classical setting considered there, a model $f$ can be converted into a model $g$ by free operations exactly when the image of $f$ is at least as large as the image of $g$. This gives a simple order on deterministic mechanisms. The quantum case is harder. As @Ansanelli_etal_2026 point out, a CPTP map is the quantum analogue of a stochastic map, not of a probability distribution over functions. This means that quantum Shannon theory, where CPTP maps play the role of channels, is not a resource theory of causal influence for the same reasons that classical Shannon theory is not one. The quantum analogue of a probability distribution over functions remains an open challenge, and finding it is necessary for developing a quantum resource theory of causal influence.

The example of non-signaling correlations makes this tension concrete. Popescu and Rohrlich showed that there are non-signaling correlations stronger than quantum correlations @Popescu_Rohrlich_1994. Thus no-signaling alone does not characterize quantum theory. The quantum set lies between the classical local polytope and the larger non-signaling polytope. One open question is why nature seems to occupy this intermediate region.

A second difficulty appears even inside the mathematical formalism of quantum correlations. Different completions of the model are not equivalent like you could see bellow. One may use finite-dimensional tensor-product models, infinite-dimensional limits, or commuting-operator models. The relation between these descriptions is connected to Tsirelson's problem and to Connes' embedding problem @Junge_Navascues_Palazuelos_PerezGarcia_Scholz_Werner_2011.

The distinction has a physical meaning. In a finite tensor-product model, Alice and Bob are described by two separate Hilbert spaces, and the joint system is represented by $cal(H)_A ⊗ cal(H)_B$. This is close to the usual laboratory picture of two separated devices. In the commuting-operator model, one uses a single Hilbert space $cal(H)$ and only requires Alice's and Bob's observables to commute, for example $A_x B_y = B_y A_x$. This algebraic condition says that the two measurements are compatible: changing their order does not change the predicted statistics. It is natural in algebraic quantum field theory, where observables localized in spacelike separated regions are required to commute. However, it is less directly tied to a finite experimental mechanism than a concrete tensor decomposition.

The issue can be stated in terms of correlation sets. Let $C_("q")$ denote the set of correlations obtained from finite-dimensional tensor-product strategies. Let $C_("qs")$ denote the spatial tensor-product model, where the Hilbert spaces may be infinite-dimensional. Let $C_("qa") := overline(C_("q"))$ denote the approximable quantum set, obtained by closing the finite-dimensional set. Finally, let $C_("qc")$ denote the commuting-operator set. These sets satisfy the inclusions
$
  C_("q") subset.eq C_("qs") subset.eq C_("qa") subset.eq C_("qc").
$
The inclusions are not only technical details. Slofstra showed that finite-dimensional quantum correlations need not form a closed set, so one can have $C_("q") != C_("qa")$ @Slofstra_2019. Tsirelson's problem asks, in one standard formulation, whether the approximable model and the commuting-operator model coincide, that is, whether $C_("qa") = C_("qc")$. The theorem $"MIP"^* = "RE"$ implies a negative answer: there are non-local games whose commuting-operator value cannot be approximated by finite-dimensional tensor-product strategies, hence $C_("qa") subset.neq C_("qc")$ @ji2022mipre.

A parallel phenomenon appears when the probabilistic gap is removed. In the zero-gap formulation of $"MIP"^*$, denoted $"MIP"_0^*$, the probabilistic gap is removed: the verifier accepts with probability exactly $1$ or strictly less than $1$. One might expect that removing the continuous probabilistic layer simplifies the problem. On the contrary, Mousavi, Nezhadi, and Yuen show that the resulting class is exactly $"coRE"$ @Mousavi_Nezhadi_Yuen_2020. Related work on commuting-operator formulations yields a similar computability-theoretic behaviour @Lin_2025_MIPco_coRE. Thus even after removing the probabilistic layer, the underlying structure remains rich. This is one motivation for the present report: interesting structure can persist at the level of exact acceptance, beyond probabilities.

These results do not decide which mathematical completion is physically real. They show a more modest point: the word "quantum" does not determine a unique operational object unless the allowed idealization is specified. A finite experiment gives finite data, with finite precision. It can rule out restricted finite-dimensional models, or give lower bounds on dimension, but it cannot by itself certify an exact infinite-dimensional Hilbert space or a genuinely non-tensor commuting-operator realization. Thus the separation $C_("qa") subset.neq C_("qc")$ is mathematically decisive, while its direct physical interpretation remains more delicate.

This motivates the constructive stance of the present report. The aim is not to decide the ontology of Hilbert spaces. It is to work at the level where the experiment is actually recorded: visible events, integer counts, compatibility equations, and finite generators. A property proved at this level has a direct operational meaning before any passage to closures, limits, or operator-algebraic completions. In this sense, staying close to the experimental record is not only a simplification. _It is a way to separate physically accessible structure from structure introduced by the mathematical completion of the model._

== From state spaces to constructive countings

Most operational reconstructions start with a space of states, a set of effects, and rules for composing systems (for exemple the General Probability Theory). This is natural when one wants to reconstruct the full probabilistic formalism. In this report, we take a different starting point. We begin with finite observations and integer counts.

The reason is simple. A normalized probability distribution erases the level at which it was obtained. For example, consider two possible events $A$ and $B$. The distribution $PP(A)=1$ and $PP(B)=0$ may come from the count $(1,0)$, from the count $(1000,0)$, or from any count $(t,0)$ with $t>0$. After normalization, all these situations become identical. Empirically, however, they are not the same: one observation and one thousand observations do not carry the same amount of evidence. Keeping integer counts preserves this scale. It also makes it possible to ask which finite pieces of data are already compatible, which are not yet complete, and which hidden generator could still close them.

The second reason is that errors in an experiment come from two fundamentally different sources. The first source is *observational error*: imprecisions in the measurement, finite resolution of detectors, or fluctuations in repeated runs. The second source is *model error*: the choice of the theoretical function $f$ that maps raw data to a reported quantity. To see why this distinction matters, consider a standard situation in physics. One measures a set of raw data $x = (x_1, dots, x_n)$, each carry some observational uncertainty $sigma_(x_i)$. A theoretical model $f:ℝ^n → ℝ$ then maps these data to a derived quantity $y = f(x_1, dots, x_n)$. The combined uncertainty on $y$ is classically estimated by propagation of errors:
$sigma_y^2 = sum_(i=1)^n lr(|(partial f) / (partial x_i)|)^2 sigma_(x_i)^2$.
Here, the $sigma_(x_i)$ reflect the first type of error, while the choice of $f$ itself carries the second type. The problem is the following. If the experimental stores only the final value $f(x)$ and its propagated uncertainty $sigma_y$, then the day the model $f$ is revised or replaced by a more accurate function $g$ derived from a new theory, then the entire experiment must be repeated. The raw data $x$ have been discarded. The information that would have allowed recomputing $g(x)$ is gone. This is one operational motivation for delaying normalization and for maintaining a record at the level of integer counts and unprocessed observations: it retains the maximal amount of information that a later, better model can exploit.

This is where contextuality enters. In the sheaf-theoretic approach, contextuality is an obstruction to gluing local data into a global section @Abramsky_Brandenburger_2011. This language is well suited to our purpose because it separates local observation from global explanation. In the discrete version used here, local probability tables are replaced by integer count tables. Compatibility becomes equality of marginal counts on overlaps. Noncontextuality becomes the possibility of reconstructing the compatible count as an integer sum of deterministic global assignments.

The change from probabilities to counts is not only cosmetic. It turns convex geometry into semigroup geometry. Instead of asking only whether a point lies in a convex hull, we ask how an integer count decomposes into irreducible generators. The Hilbert basis of the relevant semigroup then gives candidate elementary bricks of explanation. In CHSH, these bricks include local deterministic generators and lifted PR-type generators. This does not mean that PR boxes are accepted as physical final states. It means that they appear as elementary algebraic pieces of the compatible counting structure, and therefore must be interpreted.

== Quantum phenomena as unfinished stabilization

This perspective gives a useful way to read quantum phenomena. A quantum state will not be treated here as a primitive object whose meaning is already fixed. We instead ask whether some quantum features can be understood as effects of projection and incomplete stabilization. Superposition suggests that several hidden histories may give the same visible phenomenon. Entanglement suggests that local visible pieces may fail to factorize because they still come from one common hidden process.

This is deliberately only a *guiding interpretation*. The mathematical part of the report will be more modest. We start from finite observations, integer counts, and compatibility constraints. We then study the generators of these counts and the automata that describe their interrupted production. A completed compatible count is a stabilized object. A prefix is not an error; it is a partial observation that may still have possible completions. The residual future of an open generator records exactly what is missing for closure.

The aim is not to replace Hilbert spaces. It is to build a small discrete language in which such ideas can be tested. Contextuality is used as a laboratory for a broader question: how can visible phenomena be reconstructed from hidden processes without pretending that the hidden process is directly given?
